export const EMPLOYEE_DATA_POLICY = Object.freeze({ sourceType: 'GAME', note: 'Employee counts, salary, attendance, productivity, fatigue, morale and staffing values are game/estimated inputs and are not claimed as verified ICN operational data.' });

export const EMPLOYEE_CONFIG = Object.freeze({
  productivity: Object.freeze({ baseProductivity: 1, skillMultiplier: Object.freeze({ 1: 0.70, 2: 0.85, 3: 1.00, 4: 1.10, 5: 1.20 }), trainingMultiplierPerLevel: 0.04, fatigueMultiplier: 0.005, moraleMultiplier: 0.003, attendanceMultiplier: 1, maxProductivity: 1.25 }),
  fatigue: Object.freeze({ workPerHour: 6, overtimePerHour: 8, nightPerHour: 2, restPerHour: 12, breakPerHour: 20 }),
  morale: Object.freeze({ overtimePerHour: 1.0, restPerHour: 0.5, trainingGain: 1.0 }),
  attendance: Object.freeze({ absenceProbability: 0.05, sickProbability: 0.01, leaveProbability: 0 }),
  overtime: Object.freeze({ maxMinutes: 240, costMultiplier: 1.5 }),
  shift: Object.freeze({ handoverMinutes: 10, breakMinutes: 30 }),
  training: Object.freeze({ defaultDurationMinutes: 120, defaultCost: 50000, defaultSkillGain: 1, defaultProductivityGain: 0.05 }),
  staffing: Object.freeze({ defaultRequiredStaff: 0, shortageRateFloor: 0, overstaffingEnabled: true }),
  departments: Object.freeze([
    Object.freeze({ departmentId: 'AIRPORT_OPERATIONS', name: 'Airport Operations', requiredHeadcount: 20, minimumHeadcount: 5, targetHeadcount: 25, budget: 10000000 }),
    Object.freeze({ departmentId: 'SECURITY', name: 'Security', requiredHeadcount: 20, minimumHeadcount: 10, targetHeadcount: 24, budget: 12000000 }),
    Object.freeze({ departmentId: 'PASSENGER_SERVICE', name: 'Passenger Service', requiredHeadcount: 20, minimumHeadcount: 8, targetHeadcount: 24, budget: 10000000 }),
    Object.freeze({ departmentId: 'FACILITY', name: 'Facility', requiredHeadcount: 10, minimumHeadcount: 4, targetHeadcount: 12, budget: 7000000 }),
    Object.freeze({ departmentId: 'MAINTENANCE', name: 'Maintenance', requiredHeadcount: 10, minimumHeadcount: 4, targetHeadcount: 12, budget: 8000000 }),
    Object.freeze({ departmentId: 'BAGGAGE', name: 'Baggage', requiredHeadcount: 15, minimumHeadcount: 5, targetHeadcount: 18, budget: 9000000 }),
    Object.freeze({ departmentId: 'GROUND_OPERATION', name: 'Ground Operation', requiredHeadcount: 20, minimumHeadcount: 8, targetHeadcount: 24, budget: 11000000 }),
    Object.freeze({ departmentId: 'IT', name: 'IT', requiredHeadcount: 8, minimumHeadcount: 3, targetHeadcount: 10, budget: 9000000 }),
    Object.freeze({ departmentId: 'SAFETY', name: 'Safety', requiredHeadcount: 8, minimumHeadcount: 3, targetHeadcount: 10, budget: 7000000 }),
    Object.freeze({ departmentId: 'TRANSPORT', name: 'Transport', requiredHeadcount: 8, minimumHeadcount: 3, targetHeadcount: 10, budget: 6000000 }),
    Object.freeze({ departmentId: 'CARGO', name: 'Cargo', requiredHeadcount: 12, minimumHeadcount: 4, targetHeadcount: 15, budget: 8000000 }),
    Object.freeze({ departmentId: 'ADMINISTRATION', name: 'Administration', requiredHeadcount: 6, minimumHeadcount: 2, targetHeadcount: 8, budget: 6000000 }),
    Object.freeze({ departmentId: 'HR', name: 'HR', requiredHeadcount: 5, minimumHeadcount: 2, targetHeadcount: 6, budget: 5000000 }),
    Object.freeze({ departmentId: 'FINANCE', name: 'Finance', requiredHeadcount: 5, minimumHeadcount: 2, targetHeadcount: 6, budget: 5000000 }),
  ]),
  roles: Object.freeze([
    Object.freeze({ roleId: 'SecurityOfficer', departmentId: 'SECURITY', requiredSkill: 2, maxProductivity: 1.1, baseSalary: 3200000, overtimeRate: 1.5, allowedFacilities: ['SECURITY_ZONE'], queueServices: ['security'], trainingRequirements: ['SECURITY_BASIC'] }),
    Object.freeze({ roleId: 'SecuritySupervisor', departmentId: 'SECURITY', requiredSkill: 4, maxProductivity: 1.2, baseSalary: 4300000, overtimeRate: 1.5, allowedFacilities: ['SECURITY_ZONE'], queueServices: ['security'], trainingRequirements: ['SECURITY_SUPERVISOR'] }),
    Object.freeze({ roleId: 'CheckInAgent', departmentId: 'PASSENGER_SERVICE', requiredSkill: 2, maxProductivity: 1.1, baseSalary: 3000000, overtimeRate: 1.5, allowedFacilities: ['CHECK_IN_ZONE'], queueServices: ['checkin'], trainingRequirements: ['CHECKIN_BASIC'] }),
    Object.freeze({ roleId: 'InformationAgent', departmentId: 'PASSENGER_SERVICE', requiredSkill: 1, maxProductivity: 1.0, baseSalary: 2900000, overtimeRate: 1.5, allowedFacilities: ['INFORMATION_ZONE'], queueServices: [], trainingRequirements: ['SERVICE_BASIC'] }),
    Object.freeze({ roleId: 'BoardingAgent', departmentId: 'PASSENGER_SERVICE', requiredSkill: 2, maxProductivity: 1.1, baseSalary: 3000000, overtimeRate: 1.5, allowedFacilities: ['GATE'], queueServices: [], trainingRequirements: ['BOARDING_BASIC'] }),
    Object.freeze({ roleId: 'FacilityOperator', departmentId: 'FACILITY', requiredSkill: 2, maxProductivity: 1.05, baseSalary: 3100000, overtimeRate: 1.5, allowedFacilities: ['FACILITY'], queueServices: [], trainingRequirements: [] }),
    Object.freeze({ roleId: 'MaintenanceTechnician', departmentId: 'MAINTENANCE', requiredSkill: 3, maxProductivity: 1.1, baseSalary: 3500000, overtimeRate: 1.5, allowedFacilities: ['MAINTENANCE'], queueServices: [], trainingRequirements: ['MAINTENANCE_BASIC'] }),
    Object.freeze({ roleId: 'BaggageHandler', departmentId: 'BAGGAGE', requiredSkill: 2, maxProductivity: 1.05, baseSalary: 3100000, overtimeRate: 1.5, allowedFacilities: ['BAGGAGE'], queueServices: [], trainingRequirements: [] }),
    Object.freeze({ roleId: 'BaggageSupervisor', departmentId: 'BAGGAGE', requiredSkill: 4, maxProductivity: 1.15, baseSalary: 4000000, overtimeRate: 1.5, allowedFacilities: ['BAGGAGE'], queueServices: [], trainingRequirements: [] }),
    Object.freeze({ roleId: 'GroundHandler', departmentId: 'GROUND_OPERATION', requiredSkill: 2, maxProductivity: 1.05, baseSalary: 3200000, overtimeRate: 1.5, allowedFacilities: ['RAMP'], queueServices: [], trainingRequirements: [] }),
    Object.freeze({ roleId: 'RampCoordinator', departmentId: 'GROUND_OPERATION', requiredSkill: 4, maxProductivity: 1.15, baseSalary: 4100000, overtimeRate: 1.5, allowedFacilities: ['RAMP'], queueServices: [], trainingRequirements: [] }),
    Object.freeze({ roleId: 'ITSupport', departmentId: 'IT', requiredSkill: 3, maxProductivity: 1.1, baseSalary: 3800000, overtimeRate: 1.5, allowedFacilities: ['IT'], queueServices: [], trainingRequirements: [] }),
    Object.freeze({ roleId: 'SystemOperator', departmentId: 'IT', requiredSkill: 4, maxProductivity: 1.2, baseSalary: 4500000, overtimeRate: 1.5, allowedFacilities: ['IT'], queueServices: [], trainingRequirements: [] }),
  ]),
  shifts: Object.freeze([
    Object.freeze({ shiftId: 'DAY', name: 'Day', startTime: '06:00', endTime: '14:00', requiredStaff: 50, handoverMinutes: 10 }),
    Object.freeze({ shiftId: 'EVENING', name: 'Evening', startTime: '14:00', endTime: '22:00', requiredStaff: 50, handoverMinutes: 10 }),
    Object.freeze({ shiftId: 'NIGHT', name: 'Night', startTime: '22:00', endTime: '06:00', requiredStaff: 35, handoverMinutes: 10 }),
  ]),
});
