import { EMPLOYEE_CONFIG, EMPLOYEE_DATA_POLICY } from './config.js';
import { Department, Employee, EmployeeAssignment, EMPLOYEE_STATUSES, Role, Shift, Training, STAFFING_STRATEGIES } from './model.js';
import { StaffingSystem } from './staffing.js';
export class EmployeeSystem {
  constructor(simulation, { passengerSystem = null, queueEngine = null, config = EMPLOYEE_CONFIG } = {}) { if (!simulation || typeof simulation.schedule !== 'function') throw new TypeError('A SimulationCore-compatible instance is required.'); this.simulation = simulation; this.config = config; this.passengerSystem = passengerSystem; this.queueEngine = queueEngine ?? passengerSystem?.queueEngine ?? null; this.employees = new Map(); this.departments = new Map(); this.roles = new Map(); this.assignments = new Map(); this.shifts = new Map(); this.trainings = new Map(); this.staffing = new StaffingSystem({ employees: this.employees, roles: this.roles, queueEngine: this.queueEngine, config: config.productivity }); this.strategy = STAFFING_STRATEGIES.MANUAL; this.#trainingSeq = 0; this.#assignmentSeq = 0; this._overtimeCost = 0; this.#seedOrganization(); if (this.passengerSystem?.attachEmployeeSystem) this.passengerSystem.attachEmployeeSystem(this); }
  #trainingSeq; #assignmentSeq;
  #seedOrganization() { for (const d of this.config.departments) this.addDepartment(new Department(d)); for (const r of this.config.roles) this.addRole(new Role(r)); for (const s of this.config.shifts) this.addShift(new Shift(s)); }
  addDepartment(input) { const d = input instanceof Department ? input : new Department(input); if (this.departments.has(d.departmentId)) throw new Error(`Department already exists: ${d.departmentId}`); this.departments.set(d.departmentId, d); return d.departmentId; }
  addRole(input) { const r = input instanceof Role ? input : new Role(input); if (!this.departments.has(r.departmentId)) throw new Error(`Unknown department: ${r.departmentId}`); if (this.roles.has(r.roleId)) throw new Error(`Role already exists: ${r.roleId}`); this.roles.set(r.roleId, r); return r.roleId; }
  addShift(input) { const s = input instanceof Shift ? input : new Shift(input); if (this.shifts.has(s.shiftId)) throw new Error(`Shift already exists: ${s.shiftId}`); this.shifts.set(s.shiftId, s); return s.shiftId; }
  hireEmployee(input) { const role = this.roles.get(input.roleId); if (!role) throw new Error(`Unknown role: ${input.roleId}`); const employee = input instanceof Employee ? input : new Employee({ ...input, salary: input.salary ?? role.baseSalary }); if (this.employees.has(employee.employeeId)) throw new Error(`Employee already exists: ${employee.employeeId}`); this.employees.set(employee.employeeId, employee); this.departments.get(employee.departmentId).addEmployee(employee.employeeId); this.#syncDepartment(employee.departmentId); this.effectiveProductivity(employee.employeeId); return employee; }
  getEmployee(id) { return this.employees.get(id) ?? null; } listEmployees() { return [...this.employees.values()]; }
  assignEmployee(employeeId, input) { const e = this.#requireEmployee(employeeId); const role = this.roles.get(e.roleId); const allowed = role?.allowedFacilities ?? []; if (allowed.length && !allowed.some((facility) => input.facilityId === facility || input.facilityId.startsWith(`${facility}_`) || input.facilityId.startsWith(`${facility}-`)) && !(input.allowedFacilityAliases ?? []).includes(input.facilityId)) throw new Error(`Role ${e.roleId} is not allowed at ${input.facilityId}`); const assignment = new EmployeeAssignment({ ...input, employeeId, assignmentId: `assignment-${++this.#assignmentSeq}` }); this.assignments.set(assignment.assignmentId, assignment); e.currentFacilityId = assignment.facilityId; e.currentServiceType = assignment.serviceType; if (assignment.status === 'ACTIVE' && e.status === EMPLOYEE_STATUSES.OFF_DUTY) e.status = EMPLOYEE_STATUSES.AVAILABLE; this.staffing.syncAll(); const staffing = this.staffing.getFacility(assignment.facilityId); if (staffing?.queueId && this.queueEngine) { const queue = this.queueEngine.getQueue(staffing.queueId); if (queue) { const assignedCapacity = staffing.assignedStaff >= staffing.requiredStaff ? staffing.requiredStaff : staffing.effectiveServerCount; this.queueEngine.updateServiceCapacity(staffing.queueId, { serverCount: Math.max(0, assignedCapacity), serviceRateMultiplier: 1 }); } } return assignment; }
  unassignEmployee(employeeId, at = this.simulation.getSnapshot().currentTime) { const e = this.#requireEmployee(employeeId); e.currentFacilityId = null; for (const a of this.assignments.values()) if (a.employeeId === employeeId && a.status === 'ACTIVE') { a.status = 'ENDED'; a.endTime = new Date(at); } this.staffing.syncAll(); }
  registerFacilityStaffing(definition) { return this.staffing.registerFacility(definition); }
  setStaffingStrategy(strategy) { if (!Object.values(STAFFING_STRATEGIES).includes(strategy)) throw new RangeError(`Invalid staffing strategy: ${strategy}`); this.strategy = strategy; return strategy; }
  staffingRecommendations() { return this.staffing.listFacilities().filter((f) => f.staffingRatio < 1); }
  effectiveProductivity(employeeId) { const e = this.#requireEmployee(employeeId); const c = this.config.productivity; const skill = c.skillMultiplier[e.skillLevel] ?? 1; const training = 1 + e.trainingLevel * c.trainingMultiplierPerLevel; const fatigue = Math.max(0, 1 - e.fatigue * c.fatigueMultiplier); const morale = Math.max(0, 1 - Math.abs(70 - e.morale) * c.moraleMultiplier); const attendance = e.attendance * c.attendanceMultiplier; const raw = c.baseProductivity * skill * training * fatigue * morale * attendance; const role = this.roles.get(e.roleId); const cap = Math.min(c.maxProductivity, role?.maxProductivity ?? c.maxProductivity); e.productivity = Math.max(0, Math.min(cap, raw)); return e.productivity; }
  updateMorale(employeeId, delta) { const e = this.#requireEmployee(employeeId); const value = e.setMorale(e.morale + Number(delta || 0)); this.effectiveProductivity(employeeId); return value; }
  applyWorkFatigue(employeeId, minutes, { overtime = false, night = false } = {}) { const e = this.#requireEmployee(employeeId); const hours = Math.max(0, minutes) / 60; let delta = hours * this.config.fatigue.workPerHour; if (overtime) delta += hours * this.config.fatigue.overtimePerHour; if (night) delta += hours * this.config.fatigue.nightPerHour; e.setFatigue(e.fatigue + delta); this.effectiveProductivity(employeeId); return e.fatigue; }
  restEmployee(employeeId, minutes, { breakMode = false } = {}) { const e = this.#requireEmployee(employeeId); const rate = breakMode ? this.config.fatigue.breakPerHour : this.config.fatigue.restPerHour; e.setFatigue(e.fatigue - Math.max(0, minutes) / 60 * rate); this.updateMorale(employeeId, Math.max(0, minutes) / 60 * this.config.morale.restPerHour); return e.fatigue; }
  evaluateAttendance(employeeId, random = Math.random()) { const e = this.#requireEmployee(employeeId); const a = this.config.attendance; if (random < a.leaveProbability) e.status = EMPLOYEE_STATUSES.LEAVE; else if (random < a.leaveProbability + a.sickProbability) e.status = EMPLOYEE_STATUSES.SICK; else if (random < a.leaveProbability + a.sickProbability + a.absenceProbability) e.status = EMPLOYEE_STATUSES.ABSENT; else e.status = EMPLOYEE_STATUSES.AVAILABLE; e.attendance = e.isOperational() ? 1 : 0; this.effectiveProductivity(employeeId); this.staffing.syncAll(); return e.status; }
  scheduleShift(shiftId, startAt) { const shift = this.shifts.get(shiftId); if (!shift) throw new Error(`Unknown shift: ${shiftId}`); const start = new Date(startAt); const end = new Date(start.getTime() + shift.duration * 60000); this.simulation.schedule({ at: start, type: 'employee.shift.started', payload: { shiftId }, handler: ({ event }) => this.#startShift(event.payload.shiftId, event.at) }); this.simulation.schedule({ at: end, type: 'employee.shift.ended', payload: { shiftId }, handler: ({ event }) => this.#endShift(event.payload.shiftId, event.at) }); return { shiftId, start, end }; }
  #startShift(shiftId, at) { const shift = this.shifts.get(shiftId); if (!shift) return; for (const e of this.employees.values()) if (e.shiftId === shiftId && e.status !== EMPLOYEE_STATUSES.TERMINATED && e.status !== EMPLOYEE_STATUSES.TRAINING) { this.evaluateAttendance(e.employeeId); if (e.isOperational()) e.status = EMPLOYEE_STATUSES.WORKING; } this.staffing.syncAll(); shift.assignedEmployees = this.listEmployees().filter((e) => e.shiftId === shiftId).map((e) => e.employeeId); this.simulation.logger.info('EmployeeShiftStartedEvent', { shiftId, at: new Date(at).toISOString() }); }
  #endShift(shiftId, at) { const shift = this.shifts.get(shiftId); if (!shift) return; for (const e of this.employees.values()) if (e.shiftId === shiftId && [EMPLOYEE_STATUSES.WORKING, EMPLOYEE_STATUSES.OVERTIME].includes(e.status)) { const overtime = e.status === EMPLOYEE_STATUSES.OVERTIME; this.applyWorkFatigue(e.employeeId, shift.duration, { overtime, night: shiftId === 'NIGHT' }); if (!overtime) e.status = EMPLOYEE_STATUSES.OFF_DUTY; } this.staffing.syncAll(); this.simulation.logger.info('EmployeeShiftEndedEvent', { shiftId, at: new Date(at).toISOString() }); }
  startBreak(employeeId, minutes = this.config.shift.breakMinutes) { const e = this.#requireEmployee(employeeId); e.status = EMPLOYEE_STATUSES.BREAK; const at = this.simulation.getSnapshot().currentTime; this.simulation.schedule({ at: new Date(at.getTime() + minutes * 60000), type: 'employee.break.ended', payload: { employeeId }, handler: ({ event }) => { const emp = this.getEmployee(event.payload.employeeId); if (emp?.status === EMPLOYEE_STATUSES.BREAK) { this.restEmployee(emp.employeeId, minutes, { breakMode: true }); emp.status = EMPLOYEE_STATUSES.AVAILABLE; this.staffing.syncAll(); } } }); this.staffing.syncAll(); }
  startOvertime(employeeId, minutes) { const e = this.#requireEmployee(employeeId); const mins = Math.min(this.config.overtime.maxMinutes, Math.max(0, Number(minutes) || 0)); e.status = EMPLOYEE_STATUSES.OVERTIME; e.overtimeMinutes += mins; const role = this.roles.get(e.roleId); const rate = (e.salary / 160) * (role?.overtimeRate ?? this.config.overtime.costMultiplier); this._overtimeCost += rate * mins / 60; this.updateMorale(employeeId, -mins / 60 * this.config.morale.overtimePerHour); const end = new Date(this.simulation.getSnapshot().currentTime.getTime() + mins * 60000); this.simulation.schedule({ at: end, type: 'employee.overtime.ended', payload: { employeeId }, handler: ({ event }) => { const emp = this.getEmployee(event.payload.employeeId); if (emp?.status === EMPLOYEE_STATUSES.OVERTIME) emp.status = EMPLOYEE_STATUSES.OFF_DUTY; this.staffing.syncAll(); } }); this.staffing.syncAll(); return mins; }
  startTraining(employeeId, { type, duration = this.config.training.defaultDurationMinutes, cost = this.config.training.defaultCost, skillGain = this.config.training.defaultSkillGain, productivityGain = this.config.training.defaultProductivityGain } = {}) { const e = this.#requireEmployee(employeeId); const t = new Training({ trainingId: `training-${++this.#trainingSeq}`, employeeId, type, duration, cost, skillGain, productivityGain, status: 'IN_PROGRESS' }); this.trainings.set(t.trainingId, t); e.status = EMPLOYEE_STATUSES.TRAINING; this.staffing.syncAll(); const end = new Date(this.simulation.getSnapshot().currentTime.getTime() + t.duration * 60000); this.simulation.schedule({ at: end, type: 'employee.training.completed', payload: { trainingId: t.trainingId }, handler: ({ event }) => this.#completeTraining(event.payload.trainingId, event.at) }); return t; }
  #completeTraining(trainingId, at) { const t = this.trainings.get(trainingId); if (!t) return; const e = this.getEmployee(t.employeeId); if (!e) return; e.skillLevel = Math.min(5, e.skillLevel + t.skillGain); e.trainingLevel += 1; e.productivity = Math.min(this.config.productivity.maxProductivity, e.productivity + t.productivityGain); e.status = EMPLOYEE_STATUSES.AVAILABLE; t.status = 'COMPLETED'; this.updateMorale(e.employeeId, this.config.morale.trainingGain); this.staffing.syncAll(); this.simulation.logger.info('EmployeeTrainingCompletedEvent', { trainingId, at: new Date(at).toISOString() }); }
  shiftHandover(fromShiftId, toShiftId, startAt, handoverMinutes = this.config.shift.handoverMinutes) { if (!this.shifts.has(fromShiftId) || !this.shifts.has(toShiftId)) throw new Error('Unknown shift in handover.'); const t = new Date(startAt); const next = new Date(t.getTime() + Math.max(0, handoverMinutes) * 60000); this.simulation.schedule({ at: t, type: 'employee.shift.handover.started', payload: { fromShiftId, toShiftId }, handler: () => { for (const e of this.employees.values()) if (e.shiftId === fromShiftId && e.status === EMPLOYEE_STATUSES.WORKING) e.status = EMPLOYEE_STATUSES.BREAK; this.staffing.syncAll(); } }); this.simulation.schedule({ at: next, type: 'employee.shift.handover.completed', payload: { fromShiftId, toShiftId }, handler: () => { for (const e of this.employees.values()) if (e.shiftId === fromShiftId && e.status === EMPLOYEE_STATUSES.BREAK) e.status = EMPLOYEE_STATUSES.OFF_DUTY; for (const e of this.employees.values()) if (e.shiftId === toShiftId && e.isOperational()) e.status = EMPLOYEE_STATUSES.WORKING; this.staffing.syncAll(); } }); return next; }
  getFacilityStatus(id) { return this.staffing.getFacility(id); }
  statistics() { const es = this.listEmployees(); const facilities = this.staffing.listFacilities(); const avg = (key) => es.length ? es.reduce((s, e) => s + e[key], 0) / es.length : 0; const byDepartment = {}; const byRole = {}; for (const e of es) { byDepartment[e.departmentId] = (byDepartment[e.departmentId] ?? 0) + 1; byRole[e.roleId] = (byRole[e.roleId] ?? 0) + 1; } return { totalEmployees: es.length, workingEmployees: es.filter((e) => e.status === EMPLOYEE_STATUSES.WORKING).length, availableEmployees: es.filter((e) => [EMPLOYEE_STATUSES.AVAILABLE, EMPLOYEE_STATUSES.OVERTIME].includes(e.status)).length, absentEmployees: es.filter((e) => [EMPLOYEE_STATUSES.ABSENT, EMPLOYEE_STATUSES.SICK, EMPLOYEE_STATUSES.LEAVE].includes(e.status)).length, trainingEmployees: es.filter((e) => e.status === EMPLOYEE_STATUSES.TRAINING).length, overtimeEmployees: es.filter((e) => e.status === EMPLOYEE_STATUSES.OVERTIME).length, employeesByDepartment: byDepartment, employeesByRole: byRole, staffingRatio: facilities.length ? facilities.reduce((s, f) => s + f.staffingRatio, 0) / facilities.length : 1, averageFatigue: avg('fatigue'), averageMorale: avg('morale'), averageProductivity: es.length ? es.reduce((s, e) => s + this.effectiveProductivity(e.employeeId), 0) / es.length : 0, totalSalaryCost: es.filter((e) => e.status !== EMPLOYEE_STATUSES.TERMINATED).reduce((s, e) => s + e.salary, 0), totalOvertimeCost: this._overtimeCost, facilities, dataPolicy: EMPLOYEE_DATA_POLICY }; }
  #syncDepartment(id) { const d = this.departments.get(id); if (d) d.currentHeadcount = d.employeeIds.filter((x) => this.employees.has(x) && this.employees.get(x).status !== EMPLOYEE_STATUSES.TERMINATED).length; }
  #requireEmployee(id) { const e = this.getEmployee(id); if (!e) throw new Error(`Unknown employee: ${id}`); return e; }
}
