import test from 'node:test';
import assert from 'node:assert/strict';
import { SimulationCore } from '../src/simulation/index.js';
import { Flight, FlightSimulationSystem } from '../src/flights/index.js';
import { Passenger, PassengerSimulationSystem, PASSENGER_TYPES, PASSENGER_STATUSES } from '../src/passengers/index.js';
import { Employee, EmployeeSystem } from '../src/employees/index.js';
import { Baggage, BaggageScreeningResource, BaggageHandlingSystem, BAGGAGE_TYPES, BAGGAGE_STATUSES } from '../src/baggage/index.js';
import { GroundTask, GroundResource, GroundHandlingSystem, GROUND_TASK_TYPES, GROUND_TASK_STATUS, GROUND_RESOURCE_STATUS } from '../src/ground/index.js';

const START = '2026-01-01T00:00:00.000Z';
const advance = (simulation, minutes) => { simulation.resume(); simulation.tick(minutes * 60000); };
function makeFlight(overrides = {}) { return new Flight({ flightId: 'KE8', airline: 'GAME', flightNumber: 'KE8', aircraftType: 'B77W', origin: 'ICN', destination: 'NRT', scheduledArrival: START, scheduledDeparture: '2026-01-01T03:00:00.000Z', passengerCount: 10, gate: 'G-101', runway: 'RWY-1', turnaroundTime: 90, ...overrides }); }
function makeStack() { const simulation = new SimulationCore({ startDate: START }); const passengers = new PassengerSimulationSystem(simulation); const baggage = new BaggageHandlingSystem(simulation, { passengerSystem: passengers }); passengers.baggageSystem = baggage; const employees = new EmployeeSystem(simulation, { passengerSystem: passengers }); const ground = new GroundHandlingSystem(simulation, { employeeSystem: employees, baggageSystem: baggage }); baggage.attachEmployeeSystem(employees); return { simulation, passengers, baggage, employees, ground }; }
function hire(employees, id, role = 'BaggageHandler', facilityId = null) { const e = employees.hireEmployee(new Employee({ employeeId: id, name: id, departmentId: role === 'GroundHandler' ? 'GROUND_OPERATION' : role === 'SecurityOfficer' ? 'SECURITY' : 'BAGGAGE', roleId: role, skillLevel: 3 })); if (facilityId) employees.assignEmployee(id, { facilityId, serviceType: 'ground' }); return e; }

test('TEST 1: Baggage 생성', () => { const b = new Baggage({ baggageId: 'B1', flightId: 'F1', tagId: 'TAG1', weight: 20, baggageType: BAGGAGE_TYPES.CHECKED }); assert.equal(b.baggageId, 'B1'); assert.equal(b.weight, 20); assert.equal(b.currentStatus, BAGGAGE_STATUSES.CREATED); });
test('TEST 2: Passenger ↔ Baggage 연결', () => { const { passengers, baggage } = makeStack(); const p = new Passenger({ passengerId: 'P2', flightId: 'F2', terminalId: 'T1', passengerType: PASSENGER_TYPES.DEPARTURE }); passengers.addPassenger(p); const [b] = baggage.generateForPassenger(p, { count: 1 }); assert.equal(baggage.getBaggageForPassenger('P2').length, 1); assert.ok(p.baggageIds.includes(b.baggageId)); });
test('TEST 3: Flight ↔ Baggage 연결', () => { const { baggage } = makeStack(); const f = makeFlight({ flightId: 'F3', passengerCount: 0 }); const made = baggage.generateForFlight(f, { count: 3 }); assert.equal(made.length, 3); assert.equal(baggage.getBaggageForFlight('F3').length, 3); assert.equal(f.baggageCount, 3); });
test('TEST 4: Baggage Drop', () => { const { simulation, passengers, baggage } = makeStack(); const p = new Passenger({ passengerId: 'P4', flightId: 'F4', passengerType: PASSENGER_TYPES.DEPARTURE }); passengers.addPassenger(p); const [b] = baggage.onPassengerCheckInCompleted(p); assert.equal(b.currentStatus, BAGGAGE_STATUSES.BAGGAGE_DROP); advance(simulation, 2); assert.ok([BAGGAGE_STATUSES.SCREENING_QUEUE, BAGGAGE_STATUSES.SCREENING].includes(b.currentStatus)); });
test('TEST 5: Baggage Screening', () => { const { simulation, passengers, baggage } = makeStack(); const p = new Passenger({ passengerId: 'P5', flightId: 'F5', passengerType: PASSENGER_TYPES.DEPARTURE }); passengers.addPassenger(p); const [b] = baggage.onPassengerCheckInCompleted(p); advance(simulation, 4); assert.ok([BAGGAGE_STATUSES.SORTING_QUEUE, BAGGAGE_STATUSES.SORTING, BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT, BAGGAGE_STATUSES.MISROUTED].includes(b.currentStatus)); });
test('TEST 6: Baggage Sorting', () => { const { simulation, baggage } = makeStack(); const b = baggage.addBaggage({ baggageId: 'B6', flightId: 'F6', tagId: 'T6', currentStatus: BAGGAGE_STATUSES.SCREENING, origin: 'ICN', destination: 'NRT' }); baggage.queueEngine.enqueue('BAGGAGE_SORTING_QUEUE', b); advance(simulation, 3); assert.ok([BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT, BAGGAGE_STATUSES.MISROUTED].includes(b.currentStatus)); });
test('TEST 7: Baggage Loading', () => { const { simulation, baggage } = makeStack(); const b = baggage.addBaggage({ baggageId: 'B7', flightId: 'F7', tagId: 'T7', currentStatus: BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT }); baggage.queueEngine.enqueue('BAGGAGE_LOADING_QUEUE', b); advance(simulation, 5); assert.equal(b.currentStatus, BAGGAGE_STATUSES.LOADED); });
test('TEST 8: Baggage Unloading', () => { const { simulation, baggage } = makeStack(); const f = makeFlight({ flightId: 'F8', origin: 'NRT', destination: 'ICN', passengerCount: 1 }); const [b] = baggage.generateArrivalBaggage(f); baggage.unloadForFlight(f.flightId); advance(simulation, 5); assert.ok([BAGGAGE_STATUSES.TRANSFER_TO_BAGGAGE_CLAIM, BAGGAGE_STATUSES.CLAIMED].includes(b.currentStatus)); });
test('TEST 9: Baggage Claim', () => { const { simulation, baggage } = makeStack(); const f = makeFlight({ flightId: 'F9', origin: 'NRT', destination: 'ICN', passengerCount: 1 }); const [b] = baggage.generateArrivalBaggage(f); baggage.unloadForFlight(f.flightId); advance(simulation, 8); assert.equal(b.currentStatus, BAGGAGE_STATUSES.CLAIMED); });
test('TEST 10: Transfer Baggage', () => { const { simulation, baggage } = makeStack(); const f = makeFlight({ flightId: 'F10', passengerCount: 0 }); const [b] = baggage.generateTransferBaggage({ sourceFlight: f, connectionFlightId: 'KE10B', count: 1 }); baggage.processTransferBaggage(b.baggageId); advance(simulation, 3); assert.equal(b.currentStatus, BAGGAGE_STATUSES.CONNECTING_FLIGHT); });
test('TEST 11: Baggage Deadline', () => { const { baggage } = makeStack(); const f = makeFlight({ flightId: 'F11' }); assert.equal(baggage.loadingDeadline(f).toISOString(), '2026-01-01T02:35:00.000Z'); });
test('TEST 12: Baggage Readiness', () => { const { baggage } = makeStack(); const f = makeFlight({ flightId: 'F12', passengerCount: 0 }); const bs = baggage.generateForFlight(f, { count: 4 }); bs.forEach((b) => b.transitionTo(BAGGAGE_STATUSES.LOADED, { at: START, force: true })); const r = baggage.getFlightReadiness(f.flightId); assert.equal(r.requiredBaggage, 4); assert.equal(r.loadedBaggage, 4); assert.equal(r.readyRatio, 1); });
test('TEST 13: GroundTask 생성', () => { const { simulation } = makeStack(); const ground = new GroundHandlingSystem(simulation); const t = ground.createTask({ taskId: 'GT13', flightId: 'F13', taskType: GROUND_TASK_TYPES.CLEANING, requiredStaff: 1 }); assert.equal(t.taskId, 'GT13'); assert.equal(t.status, GROUND_TASK_STATUS.IN_PROGRESS); });
test('TEST 14: GroundTask Assignment', () => { const { ground, employees } = makeStack(); const facility = 'RAMP_G-14'; employees.registerFacilityStaffing({ facilityId: facility, requiredStaff: 1, allowedRoleIds: ['GroundHandler'] }); const e = hire(employees, 'E14', 'GroundHandler', facility); const t = ground.createTask({ taskId: 'GT14', flightId: 'F14', gateId: 'G-14', taskType: GROUND_TASK_TYPES.CLEANING, requiredStaff: 1, facilityId: facility }); ground.assignTask(t.taskId, [e.employeeId]); assert.deepEqual(t.assignedEmployees, [e.employeeId]); });
test('TEST 15: GroundTask Dependency', () => { const { simulation } = makeStack(); const ground = new GroundHandlingSystem(simulation); const a = ground.createTask({ taskId: 'A15', flightId: 'F15', taskType: GROUND_TASK_TYPES.CLEANING, requiredStaff: 1 }); const b = ground.createTask({ taskId: 'B15', flightId: 'F15', taskType: GROUND_TASK_TYPES.CATERING, requiredStaff: 1, dependencies: [a.taskId] }); assert.equal(b.status, GROUND_TASK_STATUS.PENDING); advance(simulation, 20); assert.equal(a.status, GROUND_TASK_STATUS.COMPLETED); assert.equal(b.status, GROUND_TASK_STATUS.COMPLETED); });
test('TEST 16: GroundTask Completion', () => { const simulation = new SimulationCore({ startDate: START }); const ground = new GroundHandlingSystem(simulation); const t = ground.createTask({ taskId: 'GT16', flightId: 'F16', taskType: GROUND_TASK_TYPES.CLEANING, requiredStaff: 1 }); advance(simulation, 20); assert.equal(t.status, GROUND_TASK_STATUS.COMPLETED); assert.ok(t.actualEndTime); });
test('TEST 17: Ground Staff Shortage', () => { const { ground, employees } = makeStack(); const facility = 'RAMP_G-17'; employees.registerFacilityStaffing({ facilityId: facility, requiredStaff: 5, allowedRoleIds: ['GroundHandler'] }); const t = ground.createTask({ taskId: 'GT17', flightId: 'F17', gateId: 'G-17', taskType: GROUND_TASK_TYPES.BAGGAGE_LOAD, requiredStaff: 5, facilityId: facility }); assert.equal(t.status, GROUND_TASK_STATUS.DELAYED); });
test('TEST 18: Ground Task Delay', () => { const { ground, employees, simulation } = makeStack(); const facility = 'RAMP_G-18'; employees.registerFacilityStaffing({ facilityId: facility, requiredStaff: 2, allowedRoleIds: ['GroundHandler'] }); const e = hire(employees, 'E18', 'GroundHandler', facility); const t = ground.createTask({ taskId: 'GT18', flightId: 'F18', gateId: 'G-18', taskType: GROUND_TASK_TYPES.BAGGAGE_LOAD, requiredStaff: 2, facilityId: facility }); ground.assignTask(t.taskId, [e.employeeId]); assert.equal(t.status, GROUND_TASK_STATUS.DELAYED); advance(simulation, 30); assert.equal(t.status, GROUND_TASK_STATUS.COMPLETED); });
test('TEST 19: Turnaround Time', () => { const { simulation, ground } = makeStack(); const f = makeFlight({ flightId: 'F19', gate: 'G-19' }); ground.onFlightStatusChange(f, 'AT_GATE'); advance(simulation, 180); ground.onFlightStatusChange(f, 'DEPARTING'); assert.ok(ground.getFlightOperations(f.flightId).turnaroundTime >= 0); });
test('TEST 20: Baggage Delay → Flight Delay Event', () => { const { simulation, baggage } = makeStack(); const f = makeFlight({ flightId: 'F20' }); baggage.onFlightStatusChange(f, 'SCHEDULED'); const b = baggage.addBaggage({ baggageId: 'B20', flightId: f.flightId, tagId: 'T20', currentStatus: BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT, deliveryDeadline: new Date('2026-01-01T01:00:00.000Z') }); baggage.closeLoading(f.flightId, new Date('2026-01-01T01:30:00.000Z')); assert.ok(f.baggageDelayMinutes >= 30); simulation.resume(); simulation.tick(60000); assert.equal(f.status, 'DELAYED'); });
test('TEST 21: Misrouting 상태', () => { const b = new Baggage({ baggageId: 'B21', flightId: 'F21', tagId: 'T21' }); b.markException(BAGGAGE_STATUSES.MISROUTED); assert.equal(b.currentStatus, BAGGAGE_STATUSES.MISROUTED); });
test('TEST 22: Missing 상태', () => { const b = new Baggage({ baggageId: 'B22', flightId: 'F22', tagId: 'T22' }); b.markException(BAGGAGE_STATUSES.MISSING); assert.equal(b.currentStatus, BAGGAGE_STATUSES.MISSING); });
test('TEST 23: Damaged 상태', () => { const b = new Baggage({ baggageId: 'B23', flightId: 'F23', tagId: 'T23' }); b.markException(BAGGAGE_STATUSES.DAMAGED); assert.equal(b.currentStatus, BAGGAGE_STATUSES.DAMAGED); });
test('TEST 24: Baggage Statistics', () => { const { baggage } = makeStack(); const s = baggage.statistics(); for (const key of ['totalBaggage','processedBaggage','screenedBaggage','sortedBaggage','loadedBaggage','unloadedBaggage','claimedBaggage','delayedBaggage','misroutedBaggage','missingBaggage','damagedBaggage','averageProcessingTime','averageSortingTime','averageLoadingTime','averageDeliveryTime']) assert.ok(key in s); });
test('TEST 25: Ground Handling Statistics', () => { const simulation = new SimulationCore({ startDate: START }); const ground = new GroundHandlingSystem(simulation); ground.addResource(new GroundResource({ resourceId: 'R25', type: 'GroundHandler', status: GROUND_RESOURCE_STATUS.WORKING })); const s = ground.statistics(); for (const key of ['totalTasks','pendingTasks','activeTasks','completedTasks','delayedTasks','averageTaskDuration','averageTurnaroundTime','staffUtilization','resourceUtilization']) assert.ok(key in s); assert.equal(s.resourceUtilization, 1); });
test('TEST 26: QueueEngine 재사용', () => { const { baggage } = makeStack(); assert.ok(baggage.getQueue('BAGGAGE_DROP_QUEUE')); assert.ok(baggage.getQueue('BAGGAGE_SCREENING_QUEUE')); assert.ok(baggage.getQueue('BAGGAGE_SORTING_QUEUE')); });
test('TEST 27: 10,000 Baggage Performance', () => { const { baggage } = makeStack(); const f = makeFlight({ flightId: 'PERF8', passengerCount: 0 }); const start = performance.now(); const made = baggage.generateForFlight(f, { count: 10000 }); const elapsed = performance.now() - start; assert.equal(made.length, 10000); assert.equal(baggage.getBaggageForFlight('PERF8').length, 10000); assert.ok(elapsed < 2500, `generation took ${elapsed.toFixed(1)}ms`); });
test('TEST 28: Flight + Gate + Runway + Passenger + Employee 회귀', () => { const { simulation, passengers, baggage, employees, ground } = makeStack(); const f = makeFlight({ flightId: 'FULL8', passengerCount: 2 }); const flights = new FlightSimulationSystem(simulation, { passengerSystem: passengers, baggageSystem: baggage, groundHandlingSystem: ground }); employees.hireEmployee(new Employee({ employeeId: 'E28', name: 'E28', departmentId: 'GROUND_OPERATION', roleId: 'GroundHandler' })); assert.doesNotThrow(() => flights.addFlight(f)); assert.ok(simulation.getSnapshot().queuedEventCount > 0); });
test('Baggage screening resource exposes required contract', () => { const r = new BaggageScreeningResource({ id: 'BSR1', terminalId: 'T1', serverCount: 4, processingRate: 100, status: 'OPEN', queue: 'BAGGAGE_SCREENING_QUEUE', capacity: 1000, failureStatus: false }); assert.equal(r.serverCount, 4); assert.equal(r.processingRate, 100); });
