import test from 'node:test';
import assert from 'node:assert/strict';
import { SimulationCore } from '../src/simulation/index.js';
import { Flight, FlightSimulationSystem } from '../src/flights/index.js';
import { PassengerSimulationSystem } from '../src/passengers/index.js';
import { Employee, EmployeeSystem, EMPLOYEE_CONFIG, EMPLOYEE_STATUSES, STAFFING_STRATEGIES } from '../src/employees/index.js';
const START = '2026-01-01T00:00:00.000Z';
const noAbsenceConfig = { ...EMPLOYEE_CONFIG, attendance: { ...EMPLOYEE_CONFIG.attendance, absenceProbability: 0, sickProbability: 0, leaveProbability: 0 } };
function makeSystem() { const simulation = new SimulationCore({ startDate: START }); const passengers = new PassengerSimulationSystem(simulation); const employees = new EmployeeSystem(simulation, { passengerSystem: passengers, config: noAbsenceConfig }); return { simulation, passengers, employees }; }
function addSecurityEmployee(employees, id, status = EMPLOYEE_STATUSES.AVAILABLE, shiftId = 'DAY', skillLevel = 3) { return employees.hireEmployee(new Employee({ employeeId: id, name: id, departmentId: 'SECURITY', roleId: 'SecurityOfficer', skillLevel, status, shiftId, salary: 3200000 })); }
function addSecurityFacility(employees, requiredStaff = 10, id = 'SECURITY_ZONE_T1_A') { employees.registerFacilityStaffing({ facilityId: id, requiredStaff, minimumStaff: 5, targetStaff: requiredStaff, queueId: 'SECURITY_QUEUE', serviceType: 'security', allowedRoleIds: ['SecurityOfficer', 'SecuritySupervisor'] }); }
test('TEST 1: Employee 생성', () => { const { employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E1001'); assert.equal(e.employeeId, 'E1001'); assert.equal(e.departmentId, 'SECURITY'); assert.equal(e.status, EMPLOYEE_STATUSES.AVAILABLE); });
test('TEST 2: Department 연결', () => { const { employees } = makeSystem(); addSecurityEmployee(employees, 'E1002'); assert.ok(employees.departments.get('SECURITY').employeeIds.includes('E1002')); });
test('TEST 3: Role 연결', () => { const { employees } = makeSystem(); addSecurityEmployee(employees, 'E1003'); assert.equal(employees.roles.get('SecurityOfficer').departmentId, 'SECURITY'); });
test('TEST 4: Employee Assignment', () => { const { employees } = makeSystem(); addSecurityEmployee(employees, 'E1004'); const a = employees.assignEmployee('E1004', { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); assert.equal(a.facilityId, 'SECURITY_ZONE_T1_A'); assert.equal(employees.getEmployee('E1004').currentFacilityId, 'SECURITY_ZONE_T1_A'); });
test('TEST 5: Staffing Requirement 계산', () => { const { employees } = makeSystem(); addSecurityFacility(employees, 10); assert.equal(employees.getFacilityStatus('SECURITY_ZONE_T1_A').requiredStaff, 10); });
test('TEST 6: Staffing Ratio 계산', () => { const { employees } = makeSystem(); addSecurityFacility(employees, 10); for (let i = 0; i < 7; i += 1) { addSecurityEmployee(employees, `E6-${i}`); employees.assignEmployee(`E6-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } const s = employees.getFacilityStatus('SECURITY_ZONE_T1_A'); assert.equal(s.assignedStaff, 7); assert.equal(s.staffingRatio, 0.7); });
test('TEST 7: Employee → Queue serverCount 연결', () => { const { employees, passengers } = makeSystem(); addSecurityFacility(employees, 10); for (let i = 0; i < 8; i += 1) { addSecurityEmployee(employees, `E7-${i}`); employees.assignEmployee(`E7-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } assert.equal(passengers.getQueue('SECURITY_QUEUE').serverCount, 8); });
test('TEST 8: 직원 부족 → 처리능력 감소', () => { const { employees, passengers } = makeSystem(); addSecurityFacility(employees, 10); for (let i = 0; i < 4; i += 1) { addSecurityEmployee(employees, `E8-${i}`); employees.assignEmployee(`E8-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } employees.getEmployee('E8-0').status = EMPLOYEE_STATUSES.ABSENT; employees.getEmployee('E8-1').status = EMPLOYEE_STATUSES.ABSENT; employees.getEmployee('E8-0').attendance = 0; employees.getEmployee('E8-1').attendance = 0; employees.staffing.syncAll(); assert.equal(passengers.getQueue('SECURITY_QUEUE').serverCount, 2); });
test('TEST 9: 직원 추가 → 처리능력 증가', () => { const { employees, passengers } = makeSystem(); addSecurityFacility(employees, 10); for (let i = 0; i < 7; i += 1) { addSecurityEmployee(employees, `E9-${i}`); employees.assignEmployee(`E9-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } addSecurityEmployee(employees, 'E9-7'); employees.assignEmployee('E9-7', { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); assert.equal(passengers.getQueue('SECURITY_QUEUE').serverCount, 8); });
test('TEST 10: Overstaffing → 비용 증가', () => { const { employees } = makeSystem(); addSecurityFacility(employees, 10); for (let i = 0; i < 20; i += 1) { addSecurityEmployee(employees, `E10-${i}`); employees.assignEmployee(`E10-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } const s = employees.getFacilityStatus('SECURITY_ZONE_T1_A'); assert.equal(s.assignedStaff, 20); assert.equal(s.overstaffedBy, 10); assert.ok(employees.statistics().totalSalaryCost > 0); });
test('TEST 11: Shift 시작', () => { const { simulation, employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E11', EMPLOYEE_STATUSES.OFF_DUTY); employees.scheduleShift('DAY', START); simulation.resume(); simulation.tick(1); assert.equal(e.status, EMPLOYEE_STATUSES.WORKING); });
test('TEST 12: Shift 종료', () => { const { simulation, employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E12', EMPLOYEE_STATUSES.OFF_DUTY); employees.scheduleShift('DAY', START); simulation.resume(); simulation.tick(1); simulation.tick(8 * 60 * 60000); assert.equal(e.status, EMPLOYEE_STATUSES.OFF_DUTY); assert.ok(e.fatigue > 0); });
test('TEST 13: Shift Handover', () => { const { simulation, employees } = makeSystem(); const a = addSecurityEmployee(employees, 'E13-A', EMPLOYEE_STATUSES.WORKING, 'DAY'); const b = addSecurityEmployee(employees, 'E13-B', EMPLOYEE_STATUSES.AVAILABLE, 'EVENING'); employees.shiftHandover('DAY', 'EVENING', START, 10); simulation.resume(); simulation.tick(1); assert.equal(a.status, EMPLOYEE_STATUSES.BREAK); simulation.tick(10 * 60000); assert.equal(a.status, EMPLOYEE_STATUSES.OFF_DUTY); assert.equal(b.status, EMPLOYEE_STATUSES.WORKING); });
test('TEST 14: Fatigue 증가', () => { const { employees } = makeSystem(); addSecurityEmployee(employees, 'E14'); const before = employees.getEmployee('E14').fatigue; employees.applyWorkFatigue('E14', 60); assert.ok(employees.getEmployee('E14').fatigue > before); });
test('TEST 15: Rest 후 Fatigue 감소', () => { const { employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E15'); employees.applyWorkFatigue('E15', 120); const before = e.fatigue; employees.restEmployee('E15', 60); assert.ok(e.fatigue < before); });
test('TEST 16: Productivity 계산', () => { const { employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E16', EMPLOYEE_STATUSES.AVAILABLE, 'DAY', 1); const low = employees.effectiveProductivity('E16'); e.skillLevel = 5; e.fatigue = 0; e.morale = 100; const high = employees.effectiveProductivity('E16'); assert.ok(high > low); });
test('TEST 17: Training', () => { const { simulation, employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E17'); const beforeSkill = e.skillLevel; const training = employees.startTraining('E17', { type: 'SECURITY_BASIC', duration: 10, skillGain: 1 }); assert.equal(e.status, EMPLOYEE_STATUSES.TRAINING); simulation.resume(); simulation.tick(10 * 60000); assert.equal(training.status, 'COMPLETED'); assert.equal(e.skillLevel, beforeSkill + 1); assert.equal(e.status, EMPLOYEE_STATUSES.AVAILABLE); });
test('TEST 18: Attendance / Absence', () => { const simulation = new SimulationCore({ startDate: START }); const employees = new EmployeeSystem(simulation, { config: EMPLOYEE_CONFIG }); addSecurityEmployee(employees, 'E18'); employees.evaluateAttendance('E18', 0); assert.ok([EMPLOYEE_STATUSES.ABSENT, EMPLOYEE_STATUSES.SICK, EMPLOYEE_STATUSES.LEAVE].includes(employees.getEmployee('E18').status)); employees.evaluateAttendance('E18', 1); assert.equal(employees.getEmployee('E18').status, EMPLOYEE_STATUSES.AVAILABLE); });
test('TEST 19: Overtime', () => { const { simulation, employees } = makeSystem(); const e = addSecurityEmployee(employees, 'E19'); const mins = employees.startOvertime('E19', 60); assert.equal(mins, 60); assert.equal(e.status, EMPLOYEE_STATUSES.OVERTIME); assert.equal(e.overtimeMinutes, 60); assert.ok(employees.statistics().totalOvertimeCost > 0); simulation.resume(); simulation.tick(60 * 60000); assert.equal(e.status, EMPLOYEE_STATUSES.OFF_DUTY); });
test('TEST 20: Employee Statistics', () => { const { employees } = makeSystem(); addSecurityEmployee(employees, 'E20'); const stats = employees.statistics(); for (const key of ['totalEmployees','workingEmployees','availableEmployees','absentEmployees','trainingEmployees','overtimeEmployees','employeesByDepartment','employeesByRole','staffingRatio','averageFatigue','averageMorale','averageProductivity','totalSalaryCost','totalOvertimeCost']) assert.ok(key in stats); });
test('TEST 21: Security Queue와 Employee 연동', () => { const { employees, passengers } = makeSystem(); addSecurityFacility(employees, 10); for (let i = 0; i < 10; i += 1) { addSecurityEmployee(employees, `E21-${i}`); employees.assignEmployee(`E21-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } assert.equal(passengers.getQueue('SECURITY_QUEUE').serverCount, 10); });
test('TEST 22: Check-in Queue와 Employee 연동', () => { const { employees, passengers } = makeSystem(); const roleId = 'CheckInAgent'; for (let i = 0; i < 6; i += 1) employees.hireEmployee(new Employee({ employeeId: `E22-${i}`, name: `E22-${i}`, departmentId: 'PASSENGER_SERVICE', roleId, skillLevel: 3 })); employees.registerFacilityStaffing({ facilityId: 'CHECK_IN_ZONE_T1', requiredStaff: 6, queueId: 'CHECK_IN_QUEUE', serviceType: 'checkin', allowedRoleIds: [roleId] }); for (let i = 0; i < 6; i += 1) employees.assignEmployee(`E22-${i}`, { facilityId: 'CHECK_IN_ZONE_T1', serviceType: 'checkin' }); assert.equal(passengers.getQueue('CHECK_IN_QUEUE').serverCount, 6); });
test('TEST 23: Immigration Queue와 Employee 연동', () => { const { employees, passengers } = makeSystem(); for (let i = 0; i < 5; i += 1) employees.hireEmployee(new Employee({ employeeId: `E23-${i}`, name: `E23-${i}`, departmentId: 'PASSENGER_SERVICE', roleId: 'CheckInAgent' })); employees.registerFacilityStaffing({ facilityId: 'IMMIGRATION_ZONE_T1', requiredStaff: 5, queueId: 'DEPARTURE_IMMIGRATION_QUEUE', serviceType: 'departure-immigration', allowedRoleIds: ['CheckInAgent'] }); for (let i = 0; i < 5; i += 1) employees.assignEmployee(`E23-${i}`, { facilityId: 'IMMIGRATION_ZONE_T1', serviceType: 'departure-immigration', allowedFacilityAliases: ['IMMIGRATION_ZONE_T1'] }); assert.equal(passengers.getQueue('DEPARTURE_IMMIGRATION_QUEUE').serverCount, 5); });
test('TEST 24: Simulation Speed 변경', () => { const { simulation } = makeSystem(); simulation.setSpeed(10); assert.equal(simulation.getSnapshot().speed, 10); });
test('TEST 25: 10,000명 Passenger + Employee Simulation 성능', () => { const { passengers, employees } = makeSystem(); addSecurityFacility(employees, 20); for (let i = 0; i < 20; i += 1) { addSecurityEmployee(employees, `E25-${i}`); employees.assignEmployee(`E25-${i}`, { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); } const flight = new Flight({ flightId: 'PERF', airline: 'GAME', flightNumber: 'PERF', aircraftType: 'GAME', origin: 'NRT', destination: 'ICN', scheduledArrival: START, scheduledDeparture: '2026-01-01T03:00:00.000Z', passengerCount: 10000 }); const start = performance.now(); passengers.generateForFlight(flight, { passengerType: 'ARRIVAL' }); employees.statistics(); const elapsed = performance.now() - start; assert.equal(passengers.getPassengersForFlight('PERF').length, 10000); assert.ok(elapsed < 2000, `simulation setup took ${elapsed.toFixed(1)}ms`); });
test('TEST 26: 기존 1~6단계 전체 회귀 테스트용 통합 생성 경로', () => { const simulation = new SimulationCore({ startDate: START }); const passengers = new PassengerSimulationSystem(simulation); const employees = new EmployeeSystem(simulation, { passengerSystem: passengers, config: noAbsenceConfig }); const flights = new FlightSimulationSystem(simulation, { passengerSystem: passengers }); const flight = new Flight({ flightId: 'KE7', airline: 'GAME', flightNumber: 'KE7', aircraftType: 'B77W', origin: 'ICN', destination: 'NRT', scheduledDeparture: '2026-01-01T03:00:00.000Z', passengerCount: 5, gate: 'G-101', runway: 'RWY-1' }); employees.setStaffingStrategy(STAFFING_STRATEGIES.MANUAL); employees.registerFacilityStaffing({ facilityId: 'SECURITY_ZONE_T1_A', requiredStaff: 2, queueId: 'SECURITY_QUEUE', allowedRoleIds: ['SecurityOfficer'] }); addSecurityEmployee(employees, 'E26-1'); addSecurityEmployee(employees, 'E26-2'); employees.assignEmployee('E26-1', { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); employees.assignEmployee('E26-2', { facilityId: 'SECURITY_ZONE_T1_A', serviceType: 'security' }); assert.doesNotThrow(() => flights.addFlight(flight)); assert.ok(simulation.getSnapshot().queuedEventCount > 0); assert.equal(passengers.getQueue('SECURITY_QUEUE').serverCount, 2); });
