import test from 'node:test';
import assert from 'node:assert/strict';
import { AirportRuntime, RUNTIME_STATUS, EVENT_CATEGORIES } from '../src/runtime/index.js';
import { Baggage } from '../src/baggage/model.js';
import { Equipment } from '../src/facilities/model.js';
const makeRuntime=(o={})=>{const r=new AirportRuntime({startDate:'2026-09-17T00:00:00.000Z',speed:60,seed:424242,autoSchedule:true,dailyFlights:24,passengersPerFlight:100,...o});r.initialize();return r;};
test('RUNTIME TEST 1 AirportRuntime creation',()=>{assert.equal(new AirportRuntime().status,RUNTIME_STATUS.CREATED);});
test('RUNTIME TEST 2 Runtime initialization',()=>{const r=makeRuntime();assert.equal(r.status,RUNTIME_STATUS.READY);});
test('RUNTIME TEST 3 Runtime state machine',()=>{const r=makeRuntime();assert.equal(r.start(),true);assert.equal(r.pause(),true);assert.equal(r.resume(),true);assert.equal(r.status,RUNTIME_STATUS.RUNNING);});
test('RUNTIME TEST 4 Dependency injection',()=>{const r=makeRuntime();assert.equal(r.flightSystem.passengerSystem,r.passengerSystem);assert.equal(r.groundSystem.facilitySystem,r.facilitySystem);});
test('RUNTIME TEST 5 Runtime startup validation',()=>{assert.ok(['PASS','WARNING'].includes(makeRuntime().realityCheck.status));});
test('RUNTIME TEST 6 Runtime snapshot',()=>{const s=makeRuntime().snapshot();assert.ok(s.simulation&&Array.isArray(s.flights)&&s.kpis);});
test('RUNTIME TEST 7 Runtime shutdown',()=>{const r=makeRuntime();r.start();assert.equal(r.stop(),true);assert.equal(r.status,RUNTIME_STATUS.STOPPED);});
test('SCHEDULE TEST 8 Daily schedule generation',()=>{const r=makeRuntime();assert.ok(r.flightSystem.getFlights().length>0&&r.scheduler.generatedDays.size===1);});
test('SCHEDULE TEST 9 Flight schedule generation',()=>{const f=makeRuntime().flightSystem.getFlights()[0];assert.ok(f.flightNumber&&f.scheduledDeparture);});
test('SCHEDULE TEST 10 Passenger demand generation',()=>{const r=makeRuntime();r.start();r.tick(3600000);assert.ok(r.passengerSystem.getPassengers().length>0);});
test('SCHEDULE TEST 11 Demand profile',()=>{const p=makeRuntime().scheduler.profile.hours;assert.equal(p.length,24);assert.notEqual(p[2].flightMultiplier,p[18].flightMultiplier);});
test('SCHEDULE TEST 12 Shift schedule',()=>{const r=makeRuntime();r.start();r.tick(8*3600000);assert.ok(r.employeeSystem.listEmployees().length>0);});
test('SCHEDULE TEST 13 Maintenance schedule',()=>{assert.ok(makeRuntime().scheduler.scheduleMaintenanceEvents);});
test('EVENT TEST 14 Scheduled Event',()=>{const r=makeRuntime();let ran=false;r.eventEngine.schedule({eventType:'TEST',category:EVENT_CATEGORIES.SCHEDULED,at:new Date(r.session.currentTime.getTime()+60000),handler:()=>ran=true});r.start();r.tick(60000);assert.equal(ran,true);});
test('EVENT TEST 15 Operational Event',()=>{const r=makeRuntime();const id=r.eventEngine.schedule({eventType:'OP',category:EVENT_CATEGORIES.OPERATIONAL,at:new Date(r.session.currentTime.getTime()+60000)});assert.equal(r.eventEngine.get(id).category,'OPERATIONAL');});
test('EVENT TEST 16 Event ordering',()=>{const r=makeRuntime();const order=[];for(const n of [1,2,3])r.eventEngine.schedule({eventType:`E${n}`,at:new Date(r.session.currentTime.getTime()+60000),handler:()=>order.push(n)});r.start();r.tick(60000);assert.deepEqual(order,[1,2,3]);});
test('EVENT TEST 17 Event priority',()=>{const r=makeRuntime();const order=[];r.eventEngine.schedule({eventType:'LOW',priority:3,at:new Date(r.session.currentTime.getTime()+60000),handler:()=>order.push('low')});r.eventEngine.schedule({eventType:'HIGH',priority:1,at:new Date(r.session.currentTime.getTime()+60000),handler:()=>order.push('high')});r.start();r.tick(60000);assert.equal(order[0],'high');});
test('EVENT TEST 18 Event cancellation',()=>{const r=makeRuntime();const id=r.eventEngine.schedule({eventType:'CANCEL',at:new Date(r.session.currentTime.getTime()+60000)});assert.equal(r.eventEngine.cancel(id),true);});
test('EVENT TEST 19 Event completion',()=>{const r=makeRuntime();const id=r.eventEngine.schedule({eventType:'DONE',at:new Date(r.session.currentTime.getTime()+60000)});r.start();r.tick(60000);assert.equal(r.eventEngine.get(id).status,'COMPLETED');});
test('TIME TEST 20 Day boundary',()=>{const r=makeRuntime({startDate:'2026-09-17T23:00:00.000Z'});r.start();r.tick(2*3600000);assert.equal(r.session.currentTime.toISOString().slice(0,10),'2026-09-18');});
test('TIME TEST 21 24-hour simulation',()=>{const r=makeRuntime({dailyFlights:8});r.start();for(let i=0;i<24;i++)r.tick(3600000);assert.ok(r.session.currentTime.getTime()-r.session.startDate.getTime()>=86400000);});
test('TIME TEST 22 Simulation speed',()=>{const r=makeRuntime();r.start();r.setSpeed(30);const b=r.session.currentTime.getTime();r.tick(1000);assert.equal(r.session.currentTime.getTime()-b,30000);});
test('INTEGRATION TEST 23 Flight daily lifecycle',()=>{const r=makeRuntime({dailyFlights:2,passengersPerFlight:20});r.start();for(let i=0;i<8;i++)r.tick(3600000);assert.ok(r.flightSystem.getFlights().some(f=>f.status));});
test('INTEGRATION TEST 24 Passenger daily lifecycle',()=>{const r=makeRuntime({dailyFlights:2});r.start();r.tick(6*3600000);assert.ok(r.passengerSystem.getPassengers().length>0);});
test('INTEGRATION TEST 25 Baggage daily lifecycle',()=>{const r=makeRuntime({dailyFlights:2});r.start();r.tick(8*3600000);assert.ok(r.baggageSystem.listBaggage().length>=0);});
test('INTEGRATION TEST 26 Ground daily lifecycle',()=>{const r=makeRuntime({dailyFlights:2});r.start();r.tick(8*3600000);assert.ok(r.groundSystem.listTasks().length>=0);});
test('INTEGRATION TEST 27 Gate integration',()=>{const r=makeRuntime();assert.ok(r.flightSystem.getFlights().some(f=>f.gate));});
test('INTEGRATION TEST 28 Runway integration',()=>{assert.equal(makeRuntime().runwaySystem.getRunways().length,4);});
test('INTEGRATION TEST 29 Employee shift integration',()=>{assert.ok(makeRuntime().employeeSystem.statistics().totalEmployees>0);});
test('INTEGRATION TEST 30 Maintenance integration',()=>{assert.ok(makeRuntime().facilitySystem.listMaintenanceTasks().length>=0);});
test('INTEGRATION TEST 31 Flight → Passenger',()=>{const r=makeRuntime({dailyFlights:2,passengersPerFlight:30});assert.ok(r.flightSystem.getFlights().some(f=>r.passengerSystem.getPassengersForFlight(f.flightId).length>0));});
test('INTEGRATION TEST 32 Passenger → Baggage',()=>{assert.ok(makeRuntime({dailyFlights:2}).baggageSystem.listBaggage().length>=0);});
test('INTEGRATION TEST 33 Baggage → Ground',()=>{assert.ok(makeRuntime({dailyFlights:2}).groundSystem.listTasks().every(t=>t.flightId));});
test('INTEGRATION TEST 34 Ground → Flight',()=>{assert.ok(makeRuntime().flightSystem.getFlights().every(f=>f.flightId));});
test('INTEGRATION TEST 35 Facility → Capacity',()=>{const f=makeRuntime().facilitySystem.getFacility('T1-BAGGAGE');assert.ok(f.availableCapacity<=f.maxCapacity);});
test('INTEGRATION TEST 36 Employee → Capacity',()=>{assert.ok(makeRuntime().employeeSystem.statistics().staffingRatio>=0);});
test('INTEGRATION TEST 37 Capacity → Queue',()=>{assert.ok(makeRuntime().passengerSystem.queueEngine.listQueues().length>0);});
test('INTEGRATION TEST 38 Queue → Delay',()=>{assert.ok(makeRuntime().passengerSystem.getQueueStats());});
test('INTEGRATION TEST 39 Delay → Turnaround',()=>{assert.ok(makeRuntime().groundSystem.statistics().averageTurnaroundTime>=0);});
test('INTEGRATION TEST 40 Turnaround → Flight',()=>{assert.ok(makeRuntime().flightSystem.getFlights().every(f=>f.turnaroundTime>=0));});
test('RANDOM TEST 41 Seed reproducibility',()=>{const a=makeRuntime({seed:99,dailyFlights:4}),b=makeRuntime({seed:99,dailyFlights:4});assert.deepEqual(a.flightSystem.getFlights().map(f=>[f.flightNumber,f.passengerCount]),b.flightSystem.getFlights().map(f=>[f.flightNumber,f.passengerCount]));});
test('RANDOM TEST 42 Different seed produces different valid result',()=>{const a=makeRuntime({seed:1,dailyFlights:4}),b=makeRuntime({seed:2,dailyFlights:4});assert.notDeepEqual(a.flightSystem.getFlights().map(f=>f.passengerCount),b.flightSystem.getFlights().map(f=>f.passengerCount));});
test('PERFORMANCE TEST 43 24h simulation',()=>{const r=makeRuntime({dailyFlights:12});r.start();const t=Date.now();for(let i=0;i<24;i++)r.tick(3600000);assert.ok(Date.now()-t<10000);});
test('PERFORMANCE TEST 44 10,000 passengers',()=>{const r=makeRuntime({autoSchedule:false});for(let i=0;i<10000;i++)r.passengerSystem.generateForFlight({flightId:`F${i}`,passengerCount:1},{count:1});assert.equal(r.passengerSystem.getPassengers().length,10000);});
test('PERFORMANCE TEST 45 10,000 baggage',()=>{const r=makeRuntime({autoSchedule:false});for(let i=0;i<10000;i++)r.baggageSystem.addBaggage(new Baggage({baggageId:`B${i}`,flightId:'PERF',tagId:`TAG${i}`,weight:10,currentStatus:'CREATED'}));assert.equal(r.baggageSystem.listBaggage().length,10000);});
test('PERFORMANCE TEST 46 1,000 equipment',()=>{const r=makeRuntime({autoSchedule:false});for(let i=0;i<1000;i++)r.facilitySystem.addEquipment(new Equipment({equipmentId:`EQ${i}`,facilityId:'T1-BAGGAGE',equipmentType:'BaggageCart'}));assert.equal(r.facilitySystem.listEquipment().length,1060);});
test('PERFORMANCE TEST 47 Long event queue',()=>{const r=makeRuntime({autoSchedule:false});for(let i=0;i<5000;i++)r.eventEngine.schedule({eventType:'LONG',at:new Date(r.session.currentTime.getTime()+i)});assert.equal(r.eventEngine.list().length,5000);});
test('UI TEST 48 Real AirportRuntime bootstrap',()=>{assert.equal(makeRuntime().status,RUNTIME_STATUS.READY);});
test('UI TEST 49 OperationsQuery receives runtime',()=>{const r=makeRuntime();assert.equal(r.operationsQuery.flights().length,r.flightSystem.getFlights().length);});
test('UI TEST 50 UI no fallback when runtime available',()=>{const r=makeRuntime();assert.ok(r.operationsRuntime===r);});
test('REGRESSION TEST 51 Stage 1~11 complete regression surface',()=>{const r=makeRuntime();assert.ok(r.simulationCore&&r.dataRegistry&&r.flightSystem&&r.passengerSystem&&r.baggageSystem&&r.groundSystem&&r.employeeSystem&&r.facilitySystem&&r.gateSystem&&r.runwaySystem);});
