import test from 'node:test';
import assert from 'node:assert/strict';
import { SimulationCore } from '../src/simulation/index.js';
import { WeatherSystem } from '../src/weather/index.js';
import { RunwaySystem } from '../src/resources/runwaySystem.js';
import { Runway } from '../src/resources/runway.js';
import { Flight } from '../src/flights/model.js';
import { FlightSimulationSystem } from '../src/flights/system.js';
import { GroundHandlingSystem } from '../src/ground/system.js';
import { AlertCenter } from '../src/ui/alerts.js';
import { OperationsQuery } from '../src/ui/query.js';
import { createAirportRuntime } from '../src/runtime/index.js';

const seq = (values) => { let i = 0; return () => values[i++ % values.length]; };
function weatherFixture(seed = 123) { const simulation = new SimulationCore({ startDate: '2026-09-17T00:00:00Z', speed: 1 }); const alertCenter = new AlertCenter(); const weather = new WeatherSystem(simulation, { random: seq([0.1, 0.2, 0.3, 0.4, 0.5]), alertCenter }); weather.initialize(); return { simulation, weather, alertCenter }; }

test('STAGE13 TEST 1 Weather creation', () => { const { weather } = weatherFixture(); const w = weather.currentWeather(); assert.ok(w.weatherId); assert.ok(w.condition); assert.equal(w.sourceType, 'ESTIMATED'); });
test('STAGE13 TEST 2 Weather timeline', () => { const { weather } = weatherFixture(); assert.ok(weather.history().length >= 1); });
test('STAGE13 TEST 3 Weather state transition', () => { const { simulation, weather } = weatherFixture(); simulation.resume(); simulation.tick(12 * 60 * 60 * 1000); assert.notEqual(weather.currentWeather().timestamp.toISOString(), '2026-09-17T00:00:00.000Z'); });
test('STAGE13 TEST 4 Seed reproducibility', () => { const a = createAirportRuntime({ seed: 777, autoSchedule: false }); const b = createAirportRuntime({ seed: 777, autoSchedule: false }); a.initialize(); b.initialize(); assert.deepEqual(a.weatherSystem.history().map(x => ({ condition:x.condition, visibility:x.visibility, windSpeed:x.windSpeed })), b.weatherSystem.history().map(x => ({ condition:x.condition, visibility:x.visibility, windSpeed:x.windSpeed }))); });
test('STAGE13 TEST 5 Weather -> Runway', () => { const simulation = new SimulationCore({ startDate: '2026-09-17T12:00:00Z' }); const weather = new WeatherSystem(simulation, { random: () => 0, profile: [{ time:'00:00', condition:'HEAVY_RAIN', probability:1, temperatureRange:[10,10], visibilityRange:[2,2], windRange:[10,10], precipitationRange:[10,10] }] }); weather.initialize(); const runways = new RunwaySystem(simulation, { weatherSystem: weather }); runways.addRunway(new Runway({ runwayId:'R1', operationType:'MIXED' })); assert.equal(runways.getOperationalCapacityMultiplier(), 0.7); });
test('STAGE13 TEST 6 Weather -> Flight Delay', () => { const simulation = new SimulationCore({ startDate: '2026-09-17T12:00:00Z' }); const weather = new WeatherSystem(simulation, { random: () => 0, profile: [{ time:'00:00', condition:'THUNDERSTORM', probability:1, temperatureRange:[10,10], visibilityRange:[1,1], windRange:[20,20], precipitationRange:[20,20] }] }); weather.initialize(); const flight = new Flight({ flightId:'WX1', airline:'SIM', flightNumber:'WX001', aircraftType:'A321', origin:'AAA', destination:'BBB', scheduledArrival:'2026-09-17T12:00:00Z', scheduledDeparture:'2026-09-17T14:00:00Z', turnaroundTime:90 }); const runway = new RunwaySystem(simulation,{weatherSystem:weather}); runway.addRunway(new Runway({runwayId:'R1',operationType:'MIXED'})); const flights = new FlightSimulationSystem(simulation,{runwaySystem:runway,weatherSystem:weather}); flights.addFlight(flight); simulation.resume(); simulation.tick(1); assert.ok(flight.weatherDelayMinutes > 0); });
test('STAGE13 TEST 7 Weather -> Ground Duration', () => { const simulation = new SimulationCore({ startDate:'2026-09-17T12:00:00Z' }); const weather = new WeatherSystem(simulation,{random:()=>0,profile:[{time:'00:00',condition:'SNOW',probability:1,temperatureRange:[0,0],visibilityRange:[3,3],windRange:[5,5],precipitationRange:[5,5]}]}); weather.initialize(); const ground = new GroundHandlingSystem(simulation,{weatherSystem:weather}); const task = ground.createTask({taskId:'GT-WX',flightId:'F-WX',taskType:'Cleaning',requiredStaff:0,dependencies:[],facilityId:'RAMP'}); assert.ok(task.estimatedEndTime - task.startTime >= 10 * 60000 * 1.35); });
test('STAGE13 TEST 8 Weather -> Alert', () => { const { alertCenter, weather } = weatherFixture(); weather.applyProfile(new Date('2026-09-17T01:00:00Z'), { time:'01:00',condition:'HEAVY_RAIN',probability:1,temperatureRange:[10,10],visibilityRange:[2,2],windRange:[10,10],precipitationRange:[10,10] }); assert.ok(alertCenter.list().some(a => a.sourceType === 'WEATHER')); });
test('STAGE13 TEST 9 Weather -> OperationsQuery', () => { const { simulation, weather } = weatherFixture(); const q = new OperationsQuery({ simulation, systems:{weather} }); assert.equal(q.weather().weatherId, weather.currentWeather().weatherId); });
test('STAGE13 TEST 10 Weather UI data', () => { const runtime = createAirportRuntime({ autoSchedule:false }); runtime.initialize(); const q = runtime.operationsQuery; assert.ok(q.weather().condition); assert.ok(Array.isArray(q.weatherHistory())); });
test('STAGE13 TEST 11 24h weather simulation', () => { const runtime = createAirportRuntime({ autoSchedule:false, speed:60 }); runtime.initialize(); runtime.start(); runtime.tick(24 * 60 * 60 * 1000 / 60); assert.ok(runtime.weatherSystem.history().length >= 12); });
test('STAGE13 TEST 12 Weather performance', () => { const simulation = new SimulationCore({ startDate:'2026-09-17T00:00:00Z' }); const weather = new WeatherSystem(simulation,{random:()=>0.25}); const t=Date.now(); weather.initialize(); for(let i=0;i<10000;i++) weather.getOperationalImpact(); assert.ok(Date.now()-t < 500); });
