import { INCIDENT_STATUS, INCIDENT_SEVERITIES, INCIDENT_DATA_POLICY } from './config.js';
export class Incident {
  constructor({ incidentId, type, severity=INCIDENT_SEVERITIES.LEVEL_2, sourceType='SYSTEM', sourceId=null, createdAt, detectedAt=null, resolvedAt=null, status=INCIDENT_STATUS.DETECTED, affectedFacilities=[], affectedFlights=[], affectedQueues=[], affectedResources=[], responseTasks=[], expectedRecoveryMinutes=30, dataType=INCIDENT_DATA_POLICY.type }) {
    if(!incidentId||!type) throw new TypeError('incidentId and type are required.'); if(!Object.values(INCIDENT_SEVERITIES).includes(Number(severity))) throw new RangeError('Invalid incident severity.'); if(!Object.values(INCIDENT_STATUS).includes(status)) throw new RangeError('Invalid incident status.');
    this.incidentId=incidentId;this.type=type;this.severity=Number(severity);this.sourceType=sourceType;this.sourceId=sourceId;this.createdAt=new Date(createdAt??Date.now());this.detectedAt=detectedAt?new Date(detectedAt):null;this.resolvedAt=resolvedAt?new Date(resolvedAt):null;this.status=status;this.affectedFacilities=[...new Set(affectedFacilities)];this.affectedFlights=[...new Set(affectedFlights)];this.affectedQueues=[...new Set(affectedQueues)];this.affectedResources=[...new Set(affectedResources)];this.responseTasks=[...new Set(responseTasks)];this.expectedRecoveryMinutes=Math.max(1,Number(expectedRecoveryMinutes)||30);this.dataType=dataType;this.timeline=[{status,at:this.createdAt}];
  }
  transitionTo(status,at,reason=null){if(!Object.values(INCIDENT_STATUS).includes(status))throw new RangeError('Invalid incident status.');this.status=status;const date=new Date(at??Date.now());if(status===INCIDENT_STATUS.DETECTED)this.detectedAt=date;if(status===INCIDENT_STATUS.RESOLVED)this.resolvedAt=date;this.timeline.push({status,at:date,reason});}
  toJSON(){return {...this,resolvedAt:this.resolvedAt?.toISOString()??null,createdAt:this.createdAt.toISOString(),detectedAt:this.detectedAt?.toISOString()??null,timeline:this.timeline.map(x=>({...x,at:x.at.toISOString()}))};}
}
export class ResponseTask {
  constructor({responseTaskId,incidentId,type,requiredRoles=[],assignedEmployeeIds=[],status='PENDING',createdAt,scheduledAt=null,completedAt=null,durationMinutes=15}){if(!responseTaskId||!incidentId||!type)throw new TypeError('responseTaskId, incidentId and type are required.');this.responseTaskId=responseTaskId;this.incidentId=incidentId;this.type=type;this.requiredRoles=[...requiredRoles];this.assignedEmployeeIds=[...assignedEmployeeIds];this.status=status;this.createdAt=new Date(createdAt??Date.now());this.scheduledAt=scheduledAt?new Date(scheduledAt):null;this.completedAt=completedAt?new Date(completedAt):null;this.durationMinutes=Math.max(1,Number(durationMinutes)||15);}
  toJSON(){return {...this,createdAt:this.createdAt.toISOString(),scheduledAt:this.scheduledAt?.toISOString()??null,completedAt:this.completedAt?.toISOString()??null};}
}
