import { GROUND_CONFIG, GROUND_DATA_POLICY } from './config.js';
import { GroundTask, GroundResource, GROUND_TASK_STATUS, GROUND_TASK_TYPES, GROUND_RESOURCE_STATUS } from './model.js';
export class GroundHandlingSystem {
  constructor(simulation,{employeeSystem=null,baggageSystem=null,facilitySystem=null,config=GROUND_CONFIG}={}){if(!simulation||typeof simulation.schedule!=='function')throw new TypeError('SimulationCore-compatible instance is required.');this.simulation=simulation;this.employeeSystem=employeeSystem;this.baggageSystem=baggageSystem;this.facilitySystem=facilitySystem;this.config=config;this.tasks=new Map();this.resources=new Map();this.flightState=new Map();this.flights=new Map();this.#seq=0;}
  #seq;
  attachFacilitySystem(system){this.facilitySystem=system;system?.attachGroundHandlingSystem?.(this);this.syncAllFacilityCapacities();return system;}
  addResource(input){const r=input instanceof GroundResource?input:new GroundResource(input);if(this.resources.has(r.resourceId))throw new Error(`Ground resource already exists: ${r.resourceId}`);this.resources.set(r.resourceId,r);return r;}
  getResource(id){return this.resources.get(id)??null;}listResources(){return [...this.resources.values()];}
  createTask(input){const t=input instanceof GroundTask?input:new GroundTask(input);if(this.tasks.has(t.taskId))throw new Error(`Ground task already exists: ${t.taskId}`);this.tasks.set(t.taskId,t);this.#scheduleIfReady(t);return t;}
  getTask(id){return this.tasks.get(id)??null;}listTasks(){return [...this.tasks.values()];}getTasksForFlight(id){return this.listTasks().filter(t=>t.flightId===id);}
  assignTask(id,employeeIds=[]){const t=this.#requireTask(id);t.assignedEmployees=[...new Set(employeeIds)];t.setStatus(GROUND_TASK_STATUS.ASSIGNED,this.simulation.getSnapshot().currentTime,'employees assigned');this.#scheduleIfReady(t);return t;}
  syncFacilityCapacity(facilityId,at=this.simulation.getSnapshot().currentTime){for(const t of this.tasks.values())if(t.facilityId===facilityId&&[GROUND_TASK_STATUS.PENDING,GROUND_TASK_STATUS.DELAYED].includes(t.status))this.#scheduleIfReady(t,at);}
  syncAllFacilityCapacities(){for(const id of new Set([...this.tasks.values()].map(t=>t.facilityId).filter(Boolean)))this.syncFacilityCapacity(id);}
  onFlightStatusChange(flight,status){this.flights.set(flight.flightId,flight);if(status==='AT_GATE'){this.#ensureFlightTasks(flight);this.flightState.set(flight.flightId,{gateOccupiedAt:this.simulation.getSnapshot().currentTime,readyAt:null,pushbackAt:null,groundDelayMinutes:0});}if(status==='READY'){const s=this.flightState.get(flight.flightId)??{};s.readyAt=this.simulation.getSnapshot().currentTime;this.flightState.set(flight.flightId,s);this.#recordDelayIfLate(flight);}if(status==='DEPARTING')this.#recordFlightTurnaround(flight.flightId,this.simulation.getSnapshot().currentTime);if(status==='LANDED')this.baggageSystem?.generateArrivalBaggage?.(flight);}
  getFlightOperations(id){const ts=this.getTasksForFlight(id);const s=this.flightState.get(id)??{};const required=ts.filter(t=>t.required);return{flightId:id,turnaroundTime:s.turnaroundTime??null,gateOccupiedAt:s.gateOccupiedAt??null,readyAt:s.readyAt??null,pushbackAt:s.pushbackAt??null,groundDelay:s.groundDelayMinutes??0,baggageDelay:this.flights.get(id)?.baggageDelayMinutes??0,requiredTaskCount:required.length,completedRequiredTaskCount:required.filter(t=>t.status===GROUND_TASK_STATUS.COMPLETED).length,activeTasks:ts.filter(t=>[GROUND_TASK_STATUS.ASSIGNED,GROUND_TASK_STATUS.IN_PROGRESS,GROUND_TASK_STATUS.DELAYED].includes(t.status)),taskStatus:ts.map(t=>({taskId:t.taskId,taskType:t.taskType,status:t.status}))};}
  statistics(){const ts=this.listTasks();const active=ts.filter(t=>[GROUND_TASK_STATUS.ASSIGNED,GROUND_TASK_STATUS.IN_PROGRESS,GROUND_TASK_STATUS.DELAYED].includes(t.status));const completed=ts.filter(t=>t.status===GROUND_TASK_STATUS.COMPLETED&&t.startTime&&t.actualEndTime);const turns=[...this.flightState.values()].map(x=>x.turnaroundTime).filter(Number.isFinite);return{totalTasks:ts.length,pendingTasks:ts.filter(t=>t.status===GROUND_TASK_STATUS.PENDING).length,activeTasks:active.length,completedTasks:completed.length,delayedTasks:ts.filter(t=>t.status===GROUND_TASK_STATUS.DELAYED).length,averageTaskDuration:completed.length?completed.reduce((s,t)=>s+(t.actualEndTime-t.startTime)/60000,0)/completed.length:0,averageTurnaroundTime:turns.length?turns.reduce((a,b)=>a+b,0)/turns.length:0,staffUtilization:active.length?active.reduce((s,t)=>s+t.assignedEmployees.length,0)/Math.max(1,active.reduce((s,t)=>s+t.requiredStaff,0)):0,resourceUtilization:this.resources.size?[...this.resources.values()].filter(r=>[GROUND_RESOURCE_STATUS.WORKING,GROUND_RESOURCE_STATUS.ASSIGNED].includes(r.status)).length/this.resources.size:0,dataPolicy:GROUND_DATA_POLICY};}
  #ensureFlightTasks(flight){if(this.getTasksForFlight(flight.flightId).length)return;const g=flight.gate??'UNKNOWN';const defs=[[GROUND_TASK_TYPES.AIRCRAFT_ARRIVAL,[]],[GROUND_TASK_TYPES.CHOCKS_PARKING,[GROUND_TASK_TYPES.AIRCRAFT_ARRIVAL]],[GROUND_TASK_TYPES.PASSENGER_DISEMBARK,[GROUND_TASK_TYPES.CHOCKS_PARKING]],[GROUND_TASK_TYPES.BAGGAGE_UNLOAD,[GROUND_TASK_TYPES.PASSENGER_DISEMBARK]],[GROUND_TASK_TYPES.CLEANING,[GROUND_TASK_TYPES.PASSENGER_DISEMBARK]],[GROUND_TASK_TYPES.CATERING,[GROUND_TASK_TYPES.CHOCKS_PARKING]],[GROUND_TASK_TYPES.REFUELING,[GROUND_TASK_TYPES.CHOCKS_PARKING]],[GROUND_TASK_TYPES.BOARDING_SUPPORT,[GROUND_TASK_TYPES.CLEANING,GROUND_TASK_TYPES.CATERING,GROUND_TASK_TYPES.REFUELING]],[GROUND_TASK_TYPES.BAGGAGE_LOAD,[GROUND_TASK_TYPES.BAGGAGE_UNLOAD,GROUND_TASK_TYPES.BOARDING_SUPPORT]],[GROUND_TASK_TYPES.PUSHBACK,[GROUND_TASK_TYPES.BAGGAGE_LOAD,GROUND_TASK_TYPES.BOARDING_SUPPORT]]];for(const [type,dependencies] of defs){const c=this.config.tasks[type];this.createTask({taskId:`${flight.flightId}-GT-${String(++this.#seq).padStart(3,'0')}`,flightId:flight.flightId,gateId:g,taskType:type,requiredStaff:c.requiredStaff,priority:this.config.taskDefaults.priority,dependencies,required:c.required,facilityId:`RAMP_${g}`});}}
  #scheduleIfReady(task,scheduledAt=this.simulation.getSnapshot().currentTime){if(!task||![GROUND_TASK_STATUS.PENDING,GROUND_TASK_STATUS.ASSIGNED,GROUND_TASK_STATUS.DELAYED].includes(task.status))return;if(!task.dependencies.every(dep=>this.getTasksForFlight(task.flightId).some(t=>(t.taskType===dep||t.taskId===dep)&&t.status===GROUND_TASK_STATUS.COMPLETED)))return;const c=this.config.tasks[task.taskType];if(!c)throw new Error(`Missing ground task config: ${task.taskType}`);const cap=this.#effectiveCapacity(task);const now=new Date(scheduledAt);if(cap<=0){if(task.status!==GROUND_TASK_STATUS.DELAYED)task.setStatus(GROUND_TASK_STATUS.DELAYED,now,'staffing/equipment shortage');this.simulation.schedule({at:new Date(now.getTime()+60000),type:'ground.task.retry',payload:{taskId:task.taskId},handler:({event})=>this.#scheduleIfReady(this.tasks.get(event.payload.taskId),event.at)});return;}task.startTime=task.startTime??new Date(now);const factor=task.requiredStaff?Math.max(0.25,task.requiredStaff/cap):1;const equipmentFactor=this.facilitySystem?.getGroundEquipmentFactor?.(task.facilityId,task.taskType)??1;const combinedFactor=equipmentFactor>0?factor/Math.max(equipmentFactor,0.01):Infinity;if(!Number.isFinite(combinedFactor)){if(task.status!==GROUND_TASK_STATUS.DELAYED)task.setStatus(GROUND_TASK_STATUS.DELAYED,now,'ground equipment unavailable');this.simulation.schedule({at:new Date(now.getTime()+60000),type:'ground.equipment.retry',payload:{taskId:task.taskId},handler:({event})=>this.#scheduleIfReady(this.tasks.get(event.payload.taskId),event.at)});return;}task.estimatedEndTime=new Date(now.getTime()+c.durationMinutes*combinedFactor*60000);task.setStatus(combinedFactor>1?GROUND_TASK_STATUS.DELAYED:GROUND_TASK_STATUS.IN_PROGRESS,now,combinedFactor>1?'reduced ground capacity':'task started');this.simulation.schedule({at:task.estimatedEndTime,type:'ground.task.completed',payload:{taskId:task.taskId},handler:({event})=>this.#completeTask(event.payload.taskId,event.at)});}
  #completeTask(id,at){const t=this.#requireTask(id);if(![GROUND_TASK_STATUS.IN_PROGRESS,GROUND_TASK_STATUS.DELAYED].includes(t.status))return;t.actualEndTime=new Date(at);if(t.status===GROUND_TASK_STATUS.DELAYED)t.delayMinutes=Math.max(0,(at-t.startTime)/60000-this.config.tasks[t.taskType].durationMinutes);t.setStatus(GROUND_TASK_STATUS.COMPLETED,at,'scheduled completion');if(t.taskType===GROUND_TASK_TYPES.BAGGAGE_UNLOAD)this.baggageSystem?.unloadForFlight?.(t.flightId,at);if(t.taskType===GROUND_TASK_TYPES.BAGGAGE_LOAD)this.baggageSystem?.loadForFlight?.(t.flightId,at);if(t.taskType===GROUND_TASK_TYPES.PUSHBACK)this.#recordFlightTurnaround(t.flightId,at);for(const n of this.getTasksForFlight(t.flightId))if(n.status===GROUND_TASK_STATUS.PENDING)this.#scheduleIfReady(n,at);this.#recordDelayIfLate(this.flights.get(t.flightId));}
  #recordFlightTurnaround(id,at){const s=this.flightState.get(id)??{};s.pushbackAt=new Date(at);s.turnaroundTime=s.gateOccupiedAt?(s.pushbackAt-s.gateOccupiedAt)/60000:null;this.flightState.set(id,s);}
  #recordDelayIfLate(flight){if(!flight)return;const s=this.flightState.get(flight.flightId)??{};const due=flight.scheduledDeparture?new Date(flight.scheduledDeparture):null;if(s.readyAt&&due&&s.readyAt>due){const d=(s.readyAt-due)/60000;s.groundDelayMinutes=Math.max(s.groundDelayMinutes??0,d);this.flightState.set(flight.flightId,s);flight.recordGroundDelay?.(d);flight.recordDelay?.(d,{at:s.readyAt,reason:'ground handling delay'});this.simulation.logger.info('GroundFlightDelayEvent',{flightId:flight.flightId,delayMinutes:d,at:s.readyAt.toISOString()});}}
  #effectiveCapacity(task){let staffCapacity=task.requiredStaff||1;if(this.employeeSystem){const employees=this.employeeSystem.listEmployees();if(!employees.length){const staffing=this.employeeSystem.getFacilityStatus?.(task.facilityId);if(staffing?.requiredStaff>0)return 0;return staffCapacity;}const roles=this.config.tasks[task.taskType]?.roleIds??[];const matching=employees.filter(e=>e.isOperational()&&(!roles.length||roles.includes(e.roleId))&&e.currentFacilityId===task.facilityId);if(!matching.length){const staffing=this.employeeSystem.getFacilityStatus?.(task.facilityId);if(staffing?.requiredStaff>0)return 0;return staffCapacity;}staffCapacity=matching.reduce((sum,e)=>sum+this.employeeSystem.effectiveProductivity(e.employeeId),0);}const equipmentFactor=this.facilitySystem?.getGroundEquipmentFactor?.(task.facilityId,task.taskType)??1;return staffCapacity*equipmentFactor;}
  #requireTask(id){const t=this.tasks.get(id);if(!t)throw new Error(`Unknown ground task: ${id}`);return t;}
}
