import { GROUND_CONFIG, GROUND_DATA_POLICY } from './config.js';
import { GroundTask, GroundResource, GROUND_TASK_STATUS, GROUND_TASK_TYPES, GROUND_RESOURCE_TYPES, GROUND_RESOURCE_STATUS } from './model.js';

export class GroundHandlingSystem {
  constructor(simulation, { employeeSystem = null, baggageSystem = null, config = GROUND_CONFIG } = {}) { if (!simulation || typeof simulation.schedule !== 'function') throw new TypeError('A SimulationCore-compatible instance is required.'); this.simulation = simulation; this.employeeSystem = employeeSystem; this.baggageSystem = baggageSystem; this.config = config; this.tasks = new Map(); this.resources = new Map(); this.flightState = new Map(); this.#seq = 0; }
  addResource(input) { const r = input instanceof GroundResource ? input : new GroundResource(input); if (this.resources.has(r.resourceId)) throw new Error(`Ground resource already exists: ${r.resourceId}`); this.resources.set(r.resourceId, r); return r; }
  getResource(id) { return this.resources.get(id) ?? null; } listResources() { return [...this.resources.values()]; }
  createTask(input) { const task = input instanceof GroundTask ? input : new GroundTask(input); if (this.tasks.has(task.taskId)) throw new Error(`Ground task already exists: ${task.taskId}`); this.tasks.set(task.taskId, task); this.simulation.logger.info('GroundTaskCreatedEvent', { taskId: task.taskId, flightId: task.flightId, taskType: task.taskType }); this.#scheduleIfReady(task); return task; }
  getTask(id) { return this.tasks.get(id) ?? null; } listTasks() { return [...this.tasks.values()]; } getTasksForFlight(flightId) { return this.listTasks().filter((t) => t.flightId === flightId); }
  assignTask(taskId, employeeIds = []) { const t = this.#requireTask(taskId); t.assignedEmployees = [...employeeIds]; t.setStatus(GROUND_TASK_STATUS.ASSIGNED, this.simulation.getSnapshot().currentTime, 'employees assigned'); return t; }
  onFlightStatusChange(flight, status) { if (status === 'AT_GATE') { this.#ensureFlightTasks(flight); this.flightState.set(flight.flightId, { gateOccupiedAt: this.simulation.getSnapshot().currentTime, readyAt: null, pushbackAt: null, groundDelayMinutes: 0 }); } if (status === 'READY') { const s = this.flightState.get(flight.flightId) ?? {}; s.readyAt = this.simulation.getSnapshot().currentTime; this.flightState.set(flight.flightId, s); this.#recordDelayIfLate(flight); } if (status === 'DEPARTING') { const s = this.flightState.get(flight.flightId) ?? {}; s.pushbackAt = this.simulation.getSnapshot().currentTime; s.turnaroundTime = s.gateOccupiedAt ? (s.pushbackAt - s.gateOccupiedAt) / 60000 : 0; this.flightState.set(flight.flightId, s); } if (status === 'LANDED') { this.baggageSystem?.generateArrivalBaggage?.(flight); } }
  getFlightOperations(flightId) { const tasks = this.getTasksForFlight(flightId); const state = this.flightState.get(flightId) ?? {}; const required = tasks.filter((t) => t.required); const completedRequired = required.filter((t) => t.status === GROUND_TASK_STATUS.COMPLETED).length; const activeTasks = tasks.filter((t) => [GROUND_TASK_STATUS.ASSIGNED, GROUND_TASK_STATUS.IN_PROGRESS, GROUND_TASK_STATUS.DELAYED].includes(t.status)); return { flightId, turnaroundTime: state.turnaroundTime ?? null, gateOccupiedAt: state.gateOccupiedAt ?? null, readyAt: state.readyAt ?? null, pushbackAt: state.pushbackAt ?? null, groundDelay: state.groundDelayMinutes ?? 0, baggageDelay: this.baggageSystem?.getFlightReadiness?.(flightId)?.readyRatio < 1 ? 1 : 0, requiredTaskCount: required.length, completedRequiredTaskCount: completedRequired, activeTasks, taskStatus: tasks.map((t) => ({ taskId: t.taskId, taskType: t.taskType, status: t.status })) }; }
  statistics() { const tasks = this.listTasks(); const active = tasks.filter((t) => [GROUND_TASK_STATUS.ASSIGNED, GROUND_TASK_STATUS.IN_PROGRESS, GROUND_TASK_STATUS.DELAYED].includes(t.status)); const completed = tasks.filter((t) => t.status === GROUND_TASK_STATUS.COMPLETED); const durations = completed.map((t) => (t.actualEndTime - t.startTime) / 60000).filter((x) => x >= 0); const turnarounds = [...this.flightState.values()].map((x) => x.turnaroundTime).filter(Number.isFinite); const resourceUtilization = this.resources.length ? this.resources.filter((r) => [GROUND_RESOURCE_STATUS.WORKING, GROUND_RESOURCE_STATUS.ASSIGNED].includes(r.status)).length / this.resources.length : 0; const staffUtilization = this.employeeSystem?.statistics?.().workingEmployees ? this.employeeSystem.statistics().workingEmployees / Math.max(1, this.employeeSystem.statistics().totalEmployees) : 0; return { totalTasks: tasks.length, pendingTasks: tasks.filter((t) => t.status === GROUND_TASK_STATUS.PENDING).length, activeTasks: active.length, completedTasks: completed.length, delayedTasks: tasks.filter((t) => t.status === GROUND_TASK_STATUS.DELAYED).length, averageTaskDuration: durations.length ? durations.reduce((a, b) => a + b, 0) / durations.length : 0, averageTurnaroundTime: turnarounds.length ? turnarounds.reduce((a, b) => a + b, 0) / turnarounds.length : 0, staffUtilization, resourceUtilization, dataPolicy: GROUND_DATA_POLICY }; }
  #ensureFlightTasks(flight) { if (this.getTasksForFlight(flight.flightId).length) return; const gateId = flight.gate ?? null; const defs = [
      [GROUND_TASK_TYPES.AIRCRAFT_ARRIVAL, []],[GROUND_TASK_TYPES.CHOCKS_PARKING, ['AircraftArrival']],[GROUND_TASK_TYPES.PASSENGER_DISEMBARK, ['ChocksParking']],[GROUND_TASK_TYPES.BAGGAGE_UNLOAD, ['PassengerDisembark']],[GROUND_TASK_TYPES.CLEANING, ['PassengerDisembark']],[GROUND_TASK_TYPES.CATERING, ['ChocksParking']],[GROUND_TASK_TYPES.REFUELING, ['ChocksParking']],[GROUND_TASK_TYPES.BOARDING_SUPPORT, ['Cleaning','Catering','Refueling']],[GROUND_TASK_TYPES.BAGGAGE_LOAD, ['BaggageUnload','BoardingSupport']],[GROUND_TASK_TYPES.PUSHBACK, ['BaggageLoad','BoardingSupport']]
    ]; for (const [type, dependencies] of defs) { const c = this.config.tasks[type]; const task = new GroundTask({ taskId: `${flight.flightId}-GT-${String(++this.#seq).padStart(3, '0')}`, flightId: flight.flightId, gateId, taskType: type, requiredStaff: c.requiredStaff, priority: this.config.taskDefaults.priority, dependencies, required: c.required }); this.createTask(task); } }
  #scheduleIfReady(task) { if (!this.#dependenciesComplete(task)) return; const c = this.config.tasks[task.taskType]; if (!c) throw new Error(`Missing ground task config: ${task.taskType}`); const capacity = this.#effectiveCapacity(task); const duration = c.durationMinutes / Math.max(capacity, 0.1); const now = this.simulation.getSnapshot().currentTime; if (capacity <= 0) { task.setStatus(GROUND_TASK_STATUS.DELAYED, now, 'staffing shortage'); this.simulation.schedule({ at: new Date(now.getTime() + 60000), type: 'ground.task.retry', payload: { taskId: task.taskId }, handler: () => this.#scheduleIfReady(task) }); return; } task.startTime = now; task.estimatedEndTime = new Date(now.getTime() + duration * 60000); task.setStatus(GROUND_TASK_STATUS.IN_PROGRESS, now, 'task started'); this.simulation.schedule({ at: task.estimatedEndTime, type: 'ground.task.completed', payload: { taskId: task.taskId }, handler: ({ event }) => this.#completeTask(event.payload.taskId, event.at) }); }
  #completeTask(taskId, at) { const task = this.#requireTask(taskId); if (task.status !== GROUND_TASK_STATUS.IN_PROGRESS) return; task.actualEndTime = new Date(at); task.setStatus(GROUND_TASK_STATUS.COMPLETED, at, 'scheduled completion'); if (task.taskType === GROUND_TASK_TYPES.BAGGAGE_UNLOAD) this.baggageSystem?.unloadForFlight?.(task.flightId, at); if (task.taskType === GROUND_TASK_TYPES.BAGGAGE_LOAD) { this.baggageSystem?.loadForFlight?.(task.flightId, at); this.#queueReadyBaggage(task.flightId, at); } if (task.taskType === GROUND_TASK_TYPES.PUSHBACK) this.#recordFlightTurnaround(task.flightId, at); this.simulation.logger.info('GroundTaskCompletedEvent', { taskId, taskType: task.taskType, at: new Date(at).toISOString() }); for (const next of this.getTasksForFlight(task.flightId)) if (next.status === GROUND_TASK_STATUS.PENDING) this.#scheduleIfReady(next); }
  #queueReadyBaggage(flightId, at) { const ready = this.baggageSystem?.getFlightReadiness?.(flightId); if (ready && ready.readyRatio < 1) { const flight = this.flightState.get(flightId) ?? {}; flight.groundDelayMinutes = (flight.groundDelayMinutes ?? 0) + Math.max(1, Math.round((1 - ready.readyRatio) * 10)); this.flightState.set(flightId, flight); this.simulation.logger.info('GroundTaskDelayedEvent', { flightId, reason: 'baggage readiness below 100%', at: new Date(at).toISOString() }); } }
  #recordFlightTurnaround(flightId, at) { const state = this.flightState.get(flightId) ?? {}; state.pushbackAt = new Date(at); state.turnaroundTime = state.gateOccupiedAt ? (state.pushbackAt - state.gateOccupiedAt) / 60000 : null; this.flightState.set(flightId, state); this.#recordDelayIfLate(null, flightId); }
  #recordDelayIfLate(flight = null, flightId = flight?.flightId) { const id = flightId; if (!id) return; const state = this.flightState.get(id); if (!state?.readyAt) return; const tasks = this.getTasksForFlight(id); const critical = tasks.filter((t) => t.required && t.status !== GROUND_TASK_STATUS.COMPLETED); if (critical.length) { const now = this.simulation.getSnapshot().currentTime; state.groundDelayMinutes = Math.max(state.groundDelayMinutes ?? 0, critical.length); this.flightState.set(id, state); this.simulation.logger.info('GroundFlightDelayEvent', { flightId: id, delayMinutes: state.groundDelayMinutes, at: now.toISOString(), reason: 'required ground task incomplete' }); } }
  #dependenciesComplete(task) { return task.dependencies.every((dep) => this.getTasksForFlight(task.flightId).some((t) => (t.taskType === dep || t.taskId === dep) && t.status === GROUND_TASK_STATUS.COMPLETED)); }
  #effectiveCapacity(task) { if (!this.employeeSystem) return task.requiredStaff > 0 ? 1 : 1; const roles = this.config.tasks[task.taskType]?.roleIds ?? []; let employees = this.employeeSystem.listEmployees().filter((e) => e.isOperational() && (!roles.length || roles.includes(e.roleId)) && e.currentFacilityId === `GROUND_${task.taskType}`); if (!employees.length) employees = this.employeeSystem.listEmployees().filter((e) => e.isOperational() && (!roles.length || roles.includes(e.roleId))); const productivity = employees.reduce((sum, e) => sum + this.employeeSystem.effectiveProductivity(e.employeeId), 0); return task.requiredStaff ? Math.min(1.5, Math.max(0, productivity / task.requiredStaff)) * task.requiredStaff : 1; }
  #requireTask(id) { const t = this.tasks.get(id); if (!t) throw new Error(`Unknown ground task: ${id}`); return t; }
}
