import { PASSENGER_ARRIVAL_MODEL, PASSENGER_SERVICE_CONFIG } from './config.js';
import { PASSENGER_STATUSES, PASSENGER_TYPES, Passenger } from './model.js';
import { QueueEngine, QUEUE_DISCIPLINES } from './queue.js';

export class PassengerSimulationSystem {
  #passengers = new Map(); #flightPassengers = new Map(); #generationBatches = new Map();
  constructor(simulation, { queueEngine = null, arrivalModel = PASSENGER_ARRIVAL_MODEL, serviceConfig = PASSENGER_SERVICE_CONFIG } = {}) { if (!simulation || typeof simulation.schedule !== 'function') throw new TypeError('A SimulationCore-compatible instance is required.'); this.simulation = simulation; this.arrivalModel = arrivalModel; this.serviceConfig = serviceConfig; this.queueEngine = queueEngine ?? new QueueEngine(simulation); this.#createDefaultQueues(); }
  addPassenger(passenger) { if (!(passenger instanceof Passenger)) throw new TypeError('Passenger instance required.'); if (this.#passengers.has(passenger.passengerId)) throw new Error(`Passenger already exists: ${passenger.passengerId}`); this.#passengers.set(passenger.passengerId, passenger); if (!this.#flightPassengers.has(passenger.flightId)) this.#flightPassengers.set(passenger.flightId, new Set()); this.#flightPassengers.get(passenger.flightId).add(passenger.passengerId); return passenger.passengerId; }
  getPassenger(id) { return this.#passengers.get(id) ?? null; } getPassengers() { return [...this.#passengers.values()]; } getPassengersForFlight(flightId) { return [...(this.#flightPassengers.get(flightId) ?? [])].map((id) => this.getPassenger(id)).filter(Boolean); }
  getQueue(id) { return this.queueEngine.getQueue(id); } getQueueStats() { return Object.fromEntries(this.queueEngine.listQueues().map((q) => [q.id, this.queueEngine.stats(q.id)])); }
  onFlightAdded(flight) { if (inferPassengerType(flight) === PASSENGER_TYPES.DEPARTURE) this.generateForFlight(flight); }
  generateForFlight(flight, { passengerType = inferPassengerType(flight), terminalId = flight.terminalId ?? null, count = flight.passengerCount } = {}) { if (!Number.isInteger(count) || count < 0) throw new RangeError('Passenger count must be a non-negative integer.'); if (count === 0) return []; if (this.#generationBatches.has(flight.flightId)) return this.getPassengersForFlight(flight.flightId).map((p) => p.passengerId); this.#generationBatches.set(flight.flightId, { count, passengerType, terminalId }); if (passengerType === PASSENGER_TYPES.DEPARTURE && (flight.scheduledDeparture ?? flight.estimatedDeparture)) { const times = distributeArrivalTimes(count, flight.scheduledDeparture ?? flight.estimatedDeparture, this.arrivalModel); const buckets = bucketTimes(times, 5); let i = 0; for (const [at, bucket] of buckets) { this.#scheduleGenerationBatch(flight, passengerType, terminalId, bucket, i); i += 1; } return []; } return this.#createBatchNow(flight, passengerType, terminalId, count, this.simulation.getSnapshot().currentTime).map((p) => p.passengerId); }
  onFlightStatusChange(flight) { if (flight.status === 'LANDED' && inferPassengerType(flight) === PASSENGER_TYPES.ARRIVAL) this.generateForFlight(flight, { passengerType: PASSENGER_TYPES.ARRIVAL }); if (flight.status === 'BOARDING') this.#startBoarding(flight); if (flight.status === 'READY') this.#finishBoarding(flight); if (flight.status === 'DEPARTING' || flight.status === 'AIRBORNE') this.#closeBoarding(flight); }
  statistics() { const passengers = this.getPassengers(); const completed = passengers.filter((p) => [PASSENGER_STATUSES.BOARDED, PASSENGER_STATUSES.COMPLETED].includes(p.status)).length; const missed = passengers.filter((p) => p.status === PASSENGER_STATUSES.MISSED_BOARDING).length; const totalWaiting = passengers.reduce((s, p) => s + p.totalWaitingTime, 0); const totalProcessing = passengers.reduce((s, p) => s + p.totalProcessingTime, 0); return { totalPassengers: passengers.length, activePassengers: Math.max(0, passengers.length - completed - missed), completedPassengers: completed, averageWaitingTime: passengers.length ? totalWaiting / passengers.length : 0, averageCheckInWaiting: aggregateQueueWait(this.queueEngine, ['CHECK_IN_QUEUE']), averageSecurityWaiting: aggregateQueueWait(this.queueEngine, ['SECURITY_QUEUE']), averageImmigrationWaiting: aggregateQueueWait(this.queueEngine, ['DEPARTURE_IMMIGRATION_QUEUE', 'ARRIVAL_IMMIGRATION_QUEUE']), maximumWaitingTime: Math.max(0, ...passengers.map((p) => p.totalWaitingTime)), missedBoarding: missed, throughput: this.queueEngine.listQueues().reduce((s, q) => s + q.completed, 0), passengerProcessingRate: this.#processingRate(), queues: this.getQueueStats(), totalWaitingMinutes: totalWaiting, totalProcessingMinutes: totalProcessing }; }
  #createDefaultQueues() {
    this.queueEngine.createQueue({ id: 'CHECK_IN_QUEUE', serviceType: 'checkin', serverCount: this.serviceConfig.checkIn.serverCount, capacity: this.serviceConfig.checkIn.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: this.serviceConfig.checkIn.serviceTimeMinutes, zone: 'CHECK_IN', processor: { onStart: (p, at) => p.transitionTo(PASSENGER_STATUSES.CHECK_IN, { at, zone: 'CHECK_IN' }), onComplete: (p, at) => { p.transitionTo(PASSENGER_STATUSES.CHECK_IN_COMPLETED, { at, zone: 'CHECK_IN' }); this.#enterSecurity(p.passengerId, at); } } });
    this.queueEngine.createQueue({ id: 'SECURITY_QUEUE', serviceType: 'security', serverCount: this.serviceConfig.security.serverCount, capacity: this.serviceConfig.security.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: this.serviceConfig.security.serviceTimeMinutes, zone: 'SECURITY', processor: { onStart: (p, at) => p.transitionTo(PASSENGER_STATUSES.SECURITY_CHECK, { at, zone: 'SECURITY' }), onComplete: (p, at) => { p.transitionTo(PASSENGER_STATUSES.SECURITY_COMPLETED, { at, zone: 'SECURITY' }); this.#enterDepartureImmigration(p.passengerId, at); } } });
    this.queueEngine.createQueue({ id: 'DEPARTURE_IMMIGRATION_QUEUE', serviceType: 'departure-immigration', serverCount: this.serviceConfig.departureImmigration.serverCount, capacity: this.serviceConfig.departureImmigration.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: this.serviceConfig.departureImmigration.serviceTimeMinutes, zone: 'DEPARTURE_IMMIGRATION', processor: { onStart: (p, at) => { p.currentZone = 'DEPARTURE_IMMIGRATION'; }, onComplete: (p, at) => { p.transitionTo(PASSENGER_STATUSES.AIRSIDE, { at, zone: 'AIRSIDE' }); p.transitionTo(PASSENGER_STATUSES.GATE_WAIT, { at, zone: `GATE_WAIT_${p.flightId}` }); } } });
    this.queueEngine.createQueue({ id: 'ARRIVAL_IMMIGRATION_QUEUE', serviceType: 'arrival-immigration', serverCount: this.serviceConfig.arrivalImmigration.serverCount, capacity: this.serviceConfig.arrivalImmigration.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: this.serviceConfig.arrivalImmigration.serviceTimeMinutes, zone: 'ARRIVAL_IMMIGRATION', processor: { onStart: (p, at) => { p.currentZone = 'ARRIVAL_IMMIGRATION'; }, onComplete: (p, at) => { p.transitionTo(PASSENGER_STATUSES.BAGGAGE_CLAIM, { at, zone: 'BAGGAGE_CLAIM' }); this.simulation.schedule({ at: new Date(at.getTime() + 2 * 60000), type: 'passenger.customs', payload: { passengerId: p.passengerId }, handler: ({ event }) => this.#arrivalPostImmigration(event.payload.passengerId, event.at) }); } } });
    this.queueEngine.createQueue({ id: 'TRANSFER_PROCESS_QUEUE', serviceType: 'transfer', serverCount: this.serviceConfig.transferProcess.serverCount, capacity: this.serviceConfig.transferProcess.capacity, discipline: QUEUE_DISCIPLINES.PRIORITY, serviceTime: this.serviceConfig.transferProcess.serviceTimeMinutes, zone: 'TRANSFER', processor: { onComplete: (p, at) => p.transitionTo(PASSENGER_STATUSES.GATE_WAIT, { at, zone: `GATE_WAIT_${p.flightId}` }) } });
  }
  #scheduleGenerationBatch(flight, type, terminalId, times, batchIndex) { const at = times[0]; this.simulation.schedule({ at, type: 'passenger.generation.batch', payload: { flightId: flight.flightId, type, terminalId, times: times.map((x) => x.toISOString()), batchIndex }, handler: ({ event }) => { const created = this.#createBatch(flight, type, terminalId, event.payload.times.map((x) => new Date(x)), event.at); this.simulation.logger.info('PassengerGenerationBatchEvent', { flightId: flight.flightId, count: created.length, batchIndex }); } }); }
  #createBatchNow(flight, type, terminalId, count, at) { return this.#createBatch(flight, type, terminalId, Array.from({ length: count }, () => new Date(at)), at); }
  #createBatch(flight, type, terminalId, times, creationAt) { const created = []; const startIndex = this.getPassengersForFlight(flight.flightId).length; times.forEach((time, offset) => { const p = new Passenger({ passengerId: `${flight.flightId}-P${String(startIndex + offset + 1).padStart(5, '0')}`, flightId: flight.flightId, terminalId, passengerType: type, origin: flight.origin, destination: flight.destination, arrivalTime: time, scheduledDeparture: flight.scheduledDeparture, currentState: type === PASSENGER_TYPES.DEPARTURE ? PASSENGER_STATUSES.CREATED : PASSENGER_STATUSES.ARRIVING_BY_AIRCRAFT, currentZone: type === PASSENGER_TYPES.DEPARTURE ? 'LANDSIDE' : 'AIRCRAFT', connectionTime: flight.connectionTime ?? null, priority: flight.operationalFlags?.emergency ? 100 : 0 }); this.addPassenger(p); created.push(p); if (type === PASSENGER_TYPES.DEPARTURE) { p.transitionTo(PASSENGER_STATUSES.ARRIVING, { at: creationAt, zone: 'LANDSIDE' }); this.simulation.schedule({ at: new Date(Math.max(time.getTime(), creationAt.getTime())), type: 'passenger.checkin.queue', payload: { passengerId: p.passengerId }, handler: ({ event }) => this.#enterCheckIn(p.passengerId, event.at) }); } else if (type === PASSENGER_TYPES.ARRIVAL) { this.simulation.schedule({ at: creationAt, type: 'passenger.deplaning', payload: { passengerId: p.passengerId }, handler: ({ event }) => { const passenger = this.getPassenger(event.payload.passengerId); if (!passenger || passenger.status !== PASSENGER_STATUSES.ARRIVING_BY_AIRCRAFT) return; passenger.transitionTo(PASSENGER_STATUSES.DEPLANING, { at: event.at, zone: 'DEPLANING' }); this.#enterArrivalImmigration(passenger.passengerId, event.at); } }); } }); return created; }
  #enterCheckIn(id, at) { const p = this.getPassenger(id); if (!p || p.status !== PASSENGER_STATUSES.ARRIVING) return; p.transitionTo(PASSENGER_STATUSES.CHECK_IN_QUEUE, { at, zone: 'CHECK_IN' }); const r = this.queueEngine.enqueue('CHECK_IN_QUEUE', p, { at }); if (!r.accepted) p.markMissedBoarding(at, 'check-in queue capacity exceeded'); }
  #enterSecurity(id, at) { const p = this.getPassenger(id); if (!p || p.status !== PASSENGER_STATUSES.CHECK_IN_COMPLETED) return; p.transitionTo(PASSENGER_STATUSES.SECURITY_QUEUE, { at, zone: 'SECURITY' }); this.queueEngine.enqueue('SECURITY_QUEUE', p, { at }); }
  #enterDepartureImmigration(id, at) { const p = this.getPassenger(id); if (!p || p.status !== PASSENGER_STATUSES.SECURITY_COMPLETED) return; p.transitionTo(PASSENGER_STATUSES.DEPARTURE_IMMIGRATION, { at, zone: 'DEPARTURE_IMMIGRATION' }); this.queueEngine.enqueue('DEPARTURE_IMMIGRATION_QUEUE', p, { at }); }
  #enterArrivalImmigration(id, at) { const p = this.getPassenger(id); if (!p || p.status !== PASSENGER_STATUSES.DEPLANING) return; p.transitionTo(PASSENGER_STATUSES.ARRIVAL_IMMIGRATION, { at, zone: 'ARRIVAL_IMMIGRATION' }); this.queueEngine.enqueue('ARRIVAL_IMMIGRATION_QUEUE', p, { at }); }
  #arrivalPostImmigration(id, at) { const p = this.getPassenger(id); if (!p || p.status !== PASSENGER_STATUSES.BAGGAGE_CLAIM) return; p.transitionTo(PASSENGER_STATUSES.CUSTOMS, { at, zone: 'CUSTOMS' }); this.simulation.schedule({ at: new Date(at.getTime() + 60000), type: 'passenger.arrival.hall', payload: { passengerId: id }, handler: ({ event }) => { const passenger = this.getPassenger(id); if (!passenger) return; passenger.transitionTo(PASSENGER_STATUSES.ARRIVAL_HALL, { at: event.at, zone: 'ARRIVAL_HALL' }); passenger.transitionTo(PASSENGER_STATUSES.COMPLETED, { at: event.at, zone: 'ARRIVAL_HALL' }); } }); }
  #startBoarding(flight) { const now = this.simulation.getSnapshot().currentTime; for (const p of this.getPassengersForFlight(flight.flightId)) if (p.status === PASSENGER_STATUSES.GATE_WAIT) p.transitionTo(PASSENGER_STATUSES.BOARDING, { at: now, zone: `GATE_${flight.gate ?? 'UNKNOWN'}` }); }
  #finishBoarding(flight) { const now = this.simulation.getSnapshot().currentTime; for (const p of this.getPassengersForFlight(flight.flightId)) { if (p.status === PASSENGER_STATUSES.BOARDING) p.transitionTo(PASSENGER_STATUSES.BOARDED, { at: now, zone: `GATE_${flight.gate ?? 'UNKNOWN'}` }); else if (p.status === PASSENGER_STATUSES.GATE_WAIT) p.transitionTo(PASSENGER_STATUSES.NOT_BOARDED, { at: now, zone: `GATE_${flight.gate ?? 'UNKNOWN'}`, force: true }); } }
  #closeBoarding(flight) { const now = this.simulation.getSnapshot().currentTime; for (const p of this.getPassengersForFlight(flight.flightId)) if ([PASSENGER_STATUSES.GATE_WAIT, PASSENGER_STATUSES.BOARDING, PASSENGER_STATUSES.NOT_BOARDED].includes(p.status)) p.markMissedBoarding(now, 'flight departed before passenger boarded'); }
  #processingRate() { const total = this.getPassengers().filter((p) => [PASSENGER_STATUSES.COMPLETED, PASSENGER_STATUSES.BOARDED].includes(p.status)).length; const starts = this.getPassengers().map((p) => p.arrivalTime?.getTime()).filter(Number.isFinite); return !total || !starts.length ? 0 : total / Math.max(1, (this.simulation.getSnapshot().currentTime.getTime() - Math.min(...starts)) / 3600000); }
}
function inferPassengerType(flight) { if (flight.passengerType && Object.values(PASSENGER_TYPES).includes(flight.passengerType)) return flight.passengerType; if (String(flight.destination).toUpperCase() === 'ICN') return PASSENGER_TYPES.ARRIVAL; return PASSENGER_TYPES.DEPARTURE; }
function distributeArrivalTimes(count, scheduled, model) { const result = []; const total = model.segments.reduce((s, x) => s + x.weight, 0); for (const segment of model.segments) { const n = Math.floor(count * segment.weight / total); for (let i = 0; i < n; i += 1) result.push(randomSegmentTime(scheduled, segment)); } while (result.length < count) result.push(randomSegmentTime(scheduled, model.segments.at(-1))); return result.sort((a, b) => a - b); }
function randomSegmentTime(scheduled, segment) { const base = new Date(scheduled).getTime(); const start = base + segment.startOffset * 60000; const end = base + segment.endOffset * 60000; return new Date(start + Math.random() * (end - start)); }
function bucketTimes(times, intervalMinutes) { const map = new Map(); for (const time of times) { const ms = Math.ceil(time.getTime() / (intervalMinutes * 60000)) * intervalMinutes * 60000; const at = new Date(ms); const key = at.toISOString(); if (!map.has(key)) map.set(key, []); map.get(key).push(time); } return [...map.entries()].sort((a, b) => new Date(a[0]) - new Date(b[0])).map(([at, values]) => [new Date(at), values]); }
function aggregateQueueWait(engine, ids) { const stats = ids.map((id) => engine.getQueue(id) ? engine.stats(id) : null).filter(Boolean); const completed = stats.reduce((s, x) => s + x.throughput, 0); return completed ? stats.reduce((s, x) => s + x.averageWaitingTime * x.throughput, 0) / completed : 0; }
