export const BAGGAGE_TYPES = Object.freeze({ CHECKED: 'CHECKED', CARRY_ON: 'CARRY_ON', TRANSFER: 'TRANSFER', SPECIAL: 'SPECIAL' });
export const BAGGAGE_STATUSES = Object.freeze({ CREATED: 'CREATED', BAGGAGE_DROP: 'BAGGAGE_DROP', ACCEPTED: 'ACCEPTED', SCREENING_QUEUE: 'SCREENING_QUEUE', SCREENING: 'SCREENING', SORTING_QUEUE: 'SORTING_QUEUE', SORTING: 'SORTING', TRANSFER_TO_AIRCRAFT: 'TRANSFER_TO_AIRCRAFT', LOADING: 'LOADING', LOADED: 'LOADED', ARRIVAL: 'ARRIVAL', UNLOADING: 'UNLOADING', TRANSFER_TO_BAGGAGE_CLAIM: 'TRANSFER_TO_BAGGAGE_CLAIM', BAGGAGE_CLAIM: 'BAGGAGE_CLAIM', CLAIMED: 'CLAIMED', ARRIVED: 'ARRIVED', TRANSFER_IDENTIFICATION: 'TRANSFER_IDENTIFICATION', TRANSFER_SORTING: 'TRANSFER_SORTING', CONNECTING_FLIGHT: 'CONNECTING_FLIGHT', MISROUTED: 'MISROUTED', DELAYED: 'DELAYED', MISSING: 'MISSING', DAMAGED: 'DAMAGED', UNABLE_TO_LOAD: 'UNABLE_TO_LOAD' });
const TERMINAL = new Set([BAGGAGE_STATUSES.CLAIMED, BAGGAGE_STATUSES.MISSING, BAGGAGE_STATUSES.DAMAGED, BAGGAGE_STATUSES.UNABLE_TO_LOAD]);
const ALLOWED = Object.freeze({ DEPARTURE: Object.freeze({ CREATED: ['BAGGAGE_DROP'], BAGGAGE_DROP: ['ACCEPTED'], ACCEPTED: ['SCREENING_QUEUE'], SCREENING_QUEUE: ['SCREENING'], SCREENING: ['SORTING_QUEUE'], SORTING_QUEUE: ['SORTING'], SORTING: ['TRANSFER_TO_AIRCRAFT'], TRANSFER_TO_AIRCRAFT: ['LOADING'], LOADING: ['LOADED'] }), ARRIVAL: Object.freeze({ LOADED: ['ARRIVAL'], ARRIVAL: ['UNLOADING'], UNLOADING: ['TRANSFER_TO_BAGGAGE_CLAIM'], TRANSFER_TO_BAGGAGE_CLAIM: ['BAGGAGE_CLAIM'], BAGGAGE_CLAIM: ['CLAIMED'] }), TRANSFER: Object.freeze({ ARRIVED: ['TRANSFER_IDENTIFICATION'], TRANSFER_IDENTIFICATION: ['TRANSFER_SORTING'], TRANSFER_SORTING: ['CONNECTING_FLIGHT'], CONNECTING_FLIGHT: ['LOADING'], LOADING: ['LOADED'] }) });
export class Baggage {
  constructor({ baggageId, passengerId = null, flightId, tagId, baggageType = BAGGAGE_TYPES.CHECKED, weight = 0, priority = 0, origin = null, destination = null, terminalId = null, currentZone = null, currentStatus = BAGGAGE_STATUSES.CREATED, createdAt = null, acceptedAt = null, screeningAt = null, sortingAt = null, loadedAt = null, unloadedAt = null, claimedAt = null, deliveryDeadline = null, connectionFlightId = null, transferStatus = null } = {}) { if (!baggageId || !flightId || !tagId) throw new TypeError('baggageId, flightId and tagId are required.'); if (!Object.values(BAGGAGE_TYPES).includes(baggageType)) throw new RangeError(`Invalid baggageType: ${baggageType}`); if (!Object.values(BAGGAGE_STATUSES).includes(currentStatus)) throw new RangeError(`Invalid baggage status: ${currentStatus}`); this.baggageId = baggageId; this.passengerId = passengerId; this.flightId = flightId; this.tagId = tagId; this.baggageType = baggageType; this.weight = Math.max(0, Number(weight) || 0); this.priority = Number.isFinite(priority) ? priority : 0; this.origin = origin; this.destination = destination; this.terminalId = terminalId; this.currentZone = currentZone; this.currentStatus = currentStatus; this.createdAt = toDate(createdAt); this.acceptedAt = toDate(acceptedAt); this.screeningAt = toDate(screeningAt); this.sortingAt = toDate(sortingAt); this.loadedAt = toDate(loadedAt); this.unloadedAt = toDate(unloadedAt); this.claimedAt = toDate(claimedAt); this.deliveryDeadline = toDate(deliveryDeadline); this.connectionFlightId = connectionFlightId; this.transferStatus = transferStatus; this.history = []; this.queueEntryTime = null; this.processingStartTime = null; this.processingEndTime = null; this.totalWaitingTime = 0; this.totalProcessingTime = 0; }
  enterQueue(at) { this.queueEntryTime = toDate(at); this.processingStartTime = null; this.processingEndTime = null; }
  startProcessing(at) { this.processingStartTime = toDate(at); if (this.queueEntryTime) this.totalWaitingTime += Math.max(0, (this.processingStartTime - this.queueEntryTime) / 60000); }
  finishProcessing(at) { this.processingEndTime = toDate(at); if (this.processingStartTime) this.totalProcessingTime += Math.max(0, (this.processingEndTime - this.processingStartTime) / 60000); }
  transitionTo(nextStatus, { at = null, zone = this.currentZone, reason = null, force = false, flow = 'DEPARTURE' } = {}) { if (!Object.values(BAGGAGE_STATUSES).includes(nextStatus)) throw new RangeError(`Invalid baggage status: ${nextStatus}`); if (TERMINAL.has(this.currentStatus) && this.currentStatus !== nextStatus && !force) throw new Error(`Cannot transition terminal baggage ${this.baggageId}.`); const choices = ALLOWED[flow]?.[this.currentStatus] ?? []; if (!force && !choices.includes(nextStatus)) throw new Error(`Invalid baggage transition ${this.currentStatus} -> ${nextStatus}`); this.currentStatus = nextStatus; this.currentZone = zone; const time = toDate(at); if (nextStatus === BAGGAGE_STATUSES.ACCEPTED) this.acceptedAt = time; if (nextStatus === BAGGAGE_STATUSES.SCREENING) this.screeningAt = time; if (nextStatus === BAGGAGE_STATUSES.SORTING) this.sortingAt = time; if (nextStatus === BAGGAGE_STATUSES.LOADED) this.loadedAt = time; if (nextStatus === BAGGAGE_STATUSES.UNLOADING) this.unloadedAt = time; if (nextStatus === BAGGAGE_STATUSES.CLAIMED) this.claimedAt = time; this.history.push({ status: nextStatus, at: time, zone, reason }); return nextStatus; }
  markException(status, { at = null, reason = null } = {}) { if (![BAGGAGE_STATUSES.MISROUTED, BAGGAGE_STATUSES.DELAYED, BAGGAGE_STATUSES.MISSING, BAGGAGE_STATUSES.DAMAGED, BAGGAGE_STATUSES.UNABLE_TO_LOAD].includes(status)) throw new RangeError('Invalid baggage exception status.'); return this.transitionTo(status, { at, reason, force: true }); }
  toJSON() { return { ...this, createdAt: iso(this.createdAt), acceptedAt: iso(this.acceptedAt), screeningAt: iso(this.screeningAt), sortingAt: iso(this.sortingAt), loadedAt: iso(this.loadedAt), unloadedAt: iso(this.unloadedAt), claimedAt: iso(this.claimedAt), deliveryDeadline: iso(this.deliveryDeadline), history: this.history.map((x) => ({ ...x, at: iso(x.at) })) }; }
}
function toDate(value) { if (value === null || value === undefined) return null; const d = new Date(value); if (Number.isNaN(d.getTime())) throw new TypeError(`Invalid date: ${value}`); return d; }
function iso(value) { return value ? value.toISOString() : null; }
