import { BAGGAGE_CONFIG, BAGGAGE_DATA_POLICY, BHS_SERVICE_TYPES } from './config.js';
import { Baggage, BAGGAGE_STATUSES, BAGGAGE_TYPES } from './model.js';
import { QueueEngine, QUEUE_DISCIPLINES } from '../passengers/queue.js';

export class BaggageHandlingSystem {
  constructor(simulation, { queueEngine = null, passengerSystem = null, employeeSystem = null, config = BAGGAGE_CONFIG } = {}) {
    if (!simulation || typeof simulation.schedule !== 'function') throw new TypeError('A SimulationCore-compatible instance is required.');
    this.simulation = simulation; this.config = config; this.passengerSystem = passengerSystem; this.employeeSystem = employeeSystem; this.queueEngine = queueEngine ?? passengerSystem?.queueEngine ?? new QueueEngine(simulation);
    this.baggage = new Map(); this.passengerBaggage = new Map(); this.flightBaggage = new Map(); this.#seq = 0; this.#setupQueues();
    if (employeeSystem) this.attachEmployeeSystem(employeeSystem);
  }
  #seq;
  attachEmployeeSystem(employeeSystem) { this.employeeSystem = employeeSystem; this.#syncStaffing(); return this.employeeSystem; }
  addBaggage(input) { const b = input instanceof Baggage ? input : new Baggage(input); if (this.baggage.has(b.baggageId)) throw new Error(`Baggage already exists: ${b.baggageId}`); this.baggage.set(b.baggageId, b); if (!this.passengerBaggage.has(b.passengerId)) this.passengerBaggage.set(b.passengerId, new Set()); if (b.passengerId) this.passengerBaggage.get(b.passengerId).add(b.baggageId); if (!this.flightBaggage.has(b.flightId)) this.flightBaggage.set(b.flightId, new Set()); this.flightBaggage.get(b.flightId).add(b.baggageId); return b; }
  getBaggage(id) { return this.baggage.get(id) ?? null; } listBaggage() { return [...this.baggage.values()]; }
  getBaggageForPassenger(passengerId) { return [...(this.passengerBaggage.get(passengerId) ?? [])].map((id) => this.getBaggage(id)).filter(Boolean); }
  getBaggageForFlight(flightId) { return [...(this.flightBaggage.get(flightId) ?? [])].map((id) => this.getBaggage(id)).filter(Boolean); }
  onPassengerCheckInCompleted(passenger, at = this.simulation.getSnapshot().currentTime) { const created = this.generateForPassenger(passenger, { at }); for (const b of created) { b.transitionTo(BAGGAGE_STATUSES.BAGGAGE_DROP, { at, zone: `BAGGAGE_DROP_${passenger.terminalId ?? 'UNKNOWN'}` }); this.queueEngine.enqueue('BAGGAGE_DROP_QUEUE', b, { at, priority: b.priority }); } return created; }
  generateForPassenger(passenger, { at = this.simulation.getSnapshot().currentTime } = {}) { if (!passenger) throw new TypeError('Passenger is required.'); if (passenger.passengerType === 'ARRIVAL') return []; const gc = this.config.generation; const p = Math.random(); let pieces = 0; if (p < gc.noneProbability) pieces = 0; else if (p < gc.noneProbability + gc.oneProbability) pieces = 1; else pieces = Math.min(gc.maxPieces, 2 + Math.floor(Math.random() * Math.max(1, gc.maxPieces - 1))); if (passenger.passengerType === 'TRANSFER') pieces = Math.min(pieces, Math.max(1, pieces)); const created = []; for (let i = 0; i < pieces; i += 1) { const weight = randomRange(gc.weightKg[0], gc.weightKg[1]); const b = this.addBaggage({ baggageId: `${passenger.flightId}-B${String(++this.#seq).padStart(6, '0')}`, passengerId: passenger.passengerId, flightId: passenger.flightId, tagId: `TAG-${passenger.flightId}-${String(this.#seq).padStart(6, '0')}`, baggageType: passenger.passengerType === 'TRANSFER' ? BAGGAGE_TYPES.TRANSFER : BAGGAGE_TYPES.CHECKED, weight, priority: this.priorityFor(passenger), origin: passenger.origin, destination: passenger.destination, terminalId: passenger.terminalId, currentZone: 'CHECK_IN', currentStatus: BAGGAGE_STATUSES.CREATED, createdAt: at, deliveryDeadline: passenger.scheduledDeparture ? new Date(new Date(passenger.scheduledDeparture).getTime() - this.config.loading.cutoffMinutes * 60000) : null, connectionFlightId: passenger.connectionFlightId ?? null }); created.push(b); } return created; }
  onFlightStatusChange(flight, status) { if (status === 'LANDED' && String(flight.destination).toUpperCase() === 'ICN') this.generateArrivalBaggage(flight); if (status === 'READY') this.checkReadiness(flight.flightId); }
  generateArrivalBaggage(flight) { const existing = this.getBaggageForFlight(flight.flightId); if (existing.length) return existing; const passengers = this.passengerSystem?.getPassengersForFlight(flight.flightId) ?? []; const source = passengers.length ? passengers : Array.from({ length: flight.passengerCount }, (_, i) => ({ passengerId: `${flight.flightId}-ARR-${i + 1}`, passengerType: 'ARRIVAL', terminalId: flight.terminalId ?? null })); const created = []; for (const p of source) { if (p.passengerType && p.passengerType !== 'ARRIVAL') continue; const b = this.addBaggage({ baggageId: `${flight.flightId}-B${String(++this.#seq).padStart(6, '0')}`, passengerId: p.passengerId ?? null, flightId: flight.flightId, tagId: `TAG-${flight.flightId}-${String(this.#seq).padStart(6, '0')}`, baggageType: BAGGAGE_TYPES.CHECKED, weight: randomRange(this.config.generation.weightKg[0], this.config.generation.weightKg[1]), priority: 0, origin: flight.origin, destination: flight.destination, terminalId: p.terminalId ?? flight.terminalId ?? null, currentZone: 'AIRCRAFT', currentStatus: BAGGAGE_STATUSES.LOADED, createdAt: this.simulation.getSnapshot().currentTime }); created.push(b); } return created; }
  processFlightArrivalBaggage(flightId, at = this.simulation.getSnapshot().currentTime) { for (const b of this.getBaggageForFlight(flightId)) if (b.currentStatus === BAGGAGE_STATUSES.LOADED) { b.transitionTo(BAGGAGE_STATUSES.ARRIVAL, { at, zone: 'AIRCRAFT' , flow: 'ARRIVAL' }); this.queueEngine.enqueue('BAGGAGE_UNLOAD_QUEUE', b, { at, priority: b.priority }); } }
  loadForFlight(flightId, at = this.simulation.getSnapshot().currentTime) { const flightBags = this.getBaggageForFlight(flightId); let loaded = 0; for (const b of flightBags) if ([BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT, BAGGAGE_STATUSES.LOADING, BAGGAGE_STATUSES.CONNECTING_FLIGHT].includes(b.currentStatus)) { if (b.deliveryDeadline && at.getTime() > b.deliveryDeadline.getTime()) { b.markException(BAGGAGE_STATUSES.UNABLE_TO_LOAD, { at, reason: 'baggage loading cutoff exceeded' }); continue; } b.transitionTo(BAGGAGE_STATUSES.LOADING, { at, zone: `AIRCRAFT_${flightId}`, force: b.currentStatus === BAGGAGE_STATUSES.CONNECTING_FLIGHT, flow: b.baggageType === BAGGAGE_TYPES.TRANSFER ? 'TRANSFER' : 'DEPARTURE' }); this.simulation.schedule({ at: new Date(at.getTime() + resolveTime(this.config.loading.serviceTimeMinutes ?? 1)), type: 'baggage.loaded', payload: { baggageId: b.baggageId }, handler: ({ event }) => { const item = this.getBaggage(event.payload.baggageId); if (!item) return; item.transitionTo(BAGGAGE_STATUSES.LOADED, { at: event.at, zone: `AIRCRAFT_${flightId}`, force: true, flow: item.baggageType === BAGGAGE_TYPES.TRANSFER ? 'TRANSFER' : 'DEPARTURE' }); } }); loaded += 1; } return loaded; }
  unloadForFlight(flightId, at = this.simulation.getSnapshot().currentTime) { this.processFlightArrivalBaggage(flightId, at); return this.getBaggageForFlight(flightId).length; }
  getFlightReadiness(flightId) { const list = this.getBaggageForFlight(flightId).filter((b) => b.baggageType !== BAGGAGE_TYPES.CARRY_ON); const requiredBaggage = list.length; const loadedBaggage = list.filter((b) => b.currentStatus === BAGGAGE_STATUSES.LOADED).length; const processedBaggage = list.filter((b) => [BAGGAGE_STATUSES.SORTING, BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT, BAGGAGE_STATUSES.LOADING, BAGGAGE_STATUSES.LOADED].includes(b.currentStatus)).length; return { flightId, requiredBaggage, processedBaggage, loadedBaggage, readyRatio: requiredBaggage ? loadedBaggage / requiredBaggage : 1 }; }
  checkReadiness(flightId) { return this.getFlightReadiness(flightId); }
  priorityFor(passenger) { const p = this.config.priority; let score = p.base; if (passenger.passengerType === 'TRANSFER') score += this.config.routing.transferPriority; if (passenger.connectionTime != null) score += p.connectionUrgencyWeight * Math.max(0, Number(passenger.connectionTime)); if (passenger.priority) score += p.departureUrgencyWeight * passenger.priority; return score; }
  statistics() { const all = this.listBaggage(); const duration = (a, b) => a && b ? Math.max(0, (b - a) / 60000) : 0; const avg = (vals) => vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : 0; return { totalBaggage: all.length, processedBaggage: all.filter((b) => b.acceptedAt || b.screeningAt || b.sortingAt || b.loadedAt).length, screenedBaggage: all.filter((b) => b.screeningAt).length, sortedBaggage: all.filter((b) => b.sortingAt).length, loadedBaggage: all.filter((b) => b.currentStatus === BAGGAGE_STATUSES.LOADED && b.loadedAt).length, unloadedBaggage: all.filter((b) => b.unloadedAt).length, claimedBaggage: all.filter((b) => b.claimedAt).length, delayedBaggage: all.filter((b) => b.currentStatus === BAGGAGE_STATUSES.DELAYED).length, misroutedBaggage: all.filter((b) => b.currentStatus === BAGGAGE_STATUSES.MISROUTED).length, missingBaggage: all.filter((b) => b.currentStatus === BAGGAGE_STATUSES.MISSING).length, damagedBaggage: all.filter((b) => b.currentStatus === BAGGAGE_STATUSES.DAMAGED).length, averageProcessingTime: avg(all.map((b) => duration(b.acceptedAt, b.loadedAt)).filter((x) => x > 0)), averageSortingTime: avg(all.map((b) => duration(b.screeningAt, b.sortingAt)).filter((x) => x > 0)), averageLoadingTime: avg(all.map((b) => duration(b.sortingAt, b.loadedAt)).filter((x) => x > 0)), averageDeliveryTime: avg(all.map((b) => duration(b.unloadedAt, b.claimedAt)).filter((x) => x > 0)), dataPolicy: BAGGAGE_DATA_POLICY }); }
  getQueueStats() { return Object.fromEntries(this.queueEngine.listQueues().filter((q) => q.serviceType.startsWith('baggage-')).map((q) => [q.id, this.queueEngine.stats(q.id)])); }
  #setupQueues() { const gc = this.config.queues; this.queueEngine.createQueue({ id: 'BAGGAGE_DROP_QUEUE', serviceType: BHS_SERVICE_TYPES.DROP, serverCount: gc.drop.serverCount, capacity: gc.drop.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: gc.drop.serviceTimeMinutes, processor: { onStart: (b, at) => b.currentZone = 'BAGGAGE_DROP', onComplete: (b, at) => { b.transitionTo(BAGGAGE_STATUSES.ACCEPTED, { at, zone: 'BHS' }); b.transitionTo(BAGGAGE_STATUSES.SCREENING_QUEUE, { at, zone: 'SCREENING' }); this.queueEngine.enqueue('BAGGAGE_SCREENING_QUEUE', b, { at, priority: b.priority }); } } });
    this.queueEngine.createQueue({ id: 'BAGGAGE_SCREENING_QUEUE', serviceType: BHS_SERVICE_TYPES.SCREENING, serverCount: gc.screening.serverCount, capacity: gc.screening.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: gc.screening.serviceTimeMinutes, processor: { onStart: (b, at) => b.transitionTo(BAGGAGE_STATUSES.SCREENING, { at, zone: 'SCREENING' }), onComplete: (b, at) => { b.transitionTo(BAGGAGE_STATUSES.SORTING_QUEUE, { at, zone: 'SORTING' }); this.queueEngine.enqueue('BAGGAGE_SORTING_QUEUE', b, { at, priority: b.priority }); } } });
    this.queueEngine.createQueue({ id: 'BAGGAGE_SORTING_QUEUE', serviceType: BHS_SERVICE_TYPES.SORTING, serverCount: gc.sorting.serverCount, capacity: gc.sorting.capacity, discipline: QUEUE_DISCIPLINES.PRIORITY, serviceTime: gc.sorting.serviceTimeMinutes, processor: { onStart: (b, at) => b.transitionTo(BAGGAGE_STATUSES.SORTING, { at, zone: `SORTING_${b.flightId}` }), onComplete: (b, at) => { b.transitionTo(BAGGAGE_STATUSES.TRANSFER_TO_AIRCRAFT, { at, zone: `TRANSFER_${b.flightId}` }); } } });
    this.queueEngine.createQueue({ id: 'BAGGAGE_LOADING_QUEUE', serviceType: BHS_SERVICE_TYPES.LOADING, serverCount: this.config.loading.serverCount, capacity: this.config.loading.capacity, discipline: QUEUE_DISCIPLINES.PRIORITY, serviceTime: this.config.loading.serviceTimeMinutes, processor: { onStart: (b, at) => { b.transitionTo(BAGGAGE_STATUSES.LOADING, { at, zone: `AIRCRAFT_${b.flightId}`, force: true, flow: b.baggageType === BAGGAGE_TYPES.TRANSFER ? 'TRANSFER' : 'DEPARTURE' }); }, onComplete: (b, at) => b.transitionTo(BAGGAGE_STATUSES.LOADED, { at, zone: `AIRCRAFT_${b.flightId}`, force: true, flow: b.baggageType === BAGGAGE_TYPES.TRANSFER ? 'TRANSFER' : 'DEPARTURE' }) } });
    this.queueEngine.createQueue({ id: 'BAGGAGE_UNLOAD_QUEUE', serviceType: BHS_SERVICE_TYPES.UNLOADING, serverCount: this.config.unloading.serverCount, capacity: this.config.unloading.capacity, discipline: QUEUE_DISCIPLINES.FIFO, serviceTime: this.config.unloading.serviceTimeMinutes, processor: { onStart: (b, at) => b.transitionTo(BAGGAGE_STATUSES.UNLOADING, { at, zone: 'AIRCRAFT', force: true, flow: 'ARRIVAL' }), onComplete: (b, at) => { b.transitionTo(BAGGAGE_STATUSES.TRANSFER_TO_BAGGAGE_CLAIM, { at, zone: 'BAGGAGE_TRANSFER', flow: 'ARRIVAL' }); this.simulation.schedule({ at: new Date(at.getTime() + this.config.delivery.claimTransferMinutes * 60000), type: 'baggage.claim.transfer', payload: { baggageId: b.baggageId }, handler: ({ event }) => { const item = this.getBaggage(event.payload.baggageId); if (!item) return; item.transitionTo(BAGGAGE_STATUSES.BAGGAGE_CLAIM, { at: event.at, zone: 'BAGGAGE_CLAIM', flow: 'ARRIVAL' }); item.transitionTo(BAGGAGE_STATUSES.CLAIMED, { at: event.at, zone: 'BAGGAGE_CLAIM', flow: 'ARRIVAL' }); } }); } } }); }
  #syncStaffing() { if (!this.employeeSystem) return; const mappings = [{ facilityId: 'BAGGAGE_DROP', queueId: 'BAGGAGE_DROP_QUEUE', requiredStaff: this.config.queues.drop.serverCount, roles: ['BaggageHandler', 'GroundHandler'] }, { facilityId: 'BAGGAGE_SCREENING', queueId: 'BAGGAGE_SCREENING_QUEUE', requiredStaff: this.config.queues.screening.serverCount, roles: ['SecurityOfficer', 'BaggageHandler'] }, { facilityId: 'BAGGAGE_SORTING', queueId: 'BAGGAGE_SORTING_QUEUE', requiredStaff: this.config.queues.sorting.serverCount, roles: ['BaggageHandler'] }, { facilityId: 'BAGGAGE_LOADING', queueId: 'BAGGAGE_LOADING_QUEUE', requiredStaff: this.config.loading.serverCount, roles: ['BaggageHandler', 'GroundHandler'] }, { facilityId: 'BAGGAGE_UNLOADING', queueId: 'BAGGAGE_UNLOAD_QUEUE', requiredStaff: this.config.unloading.serverCount, roles: ['BaggageHandler', 'GroundHandler'] }]; for (const m of mappings) this.employeeSystem.registerFacilityStaffing({ facilityId: m.facilityId, requiredStaff: m.requiredStaff, queueId: m.queueId, allowedRoleIds: m.roles }); this.employeeSystem.staffing.syncAll(); }
}
function randomRange(min, max) { return Number(min) + Math.random() * (Number(max) - Number(min)); }
function resolveTime(spec) { if (Array.isArray(spec)) return randomRange(spec[0], spec[1]) * 60000; return Number(spec) * 60000; }
